export enum V4MixedQuoterActions {
  SS_2_EXACT_INPUT_SINGLE = 0,
  SS_3_EXACT_INPUT_SINGLE = 1,
  V2_EXACT_INPUT_SINGLE = 2,
  V3_EXACT_INPUT_SINGLE = 3,
  V4_CL_EXACT_INPUT_SINGLE = 4,
  V4_BIN_EXACT_INPUT_SINGLE = 5,
}
