packages:
  - 'packages/*'
  - 'packages/routing-sdk/**'
  - 'apps/*'
  - 'apis/*'
  - 'examples/*'
  - 'scripts'

catalog:
  viem: ^2.21.22
  wagmi: ^2.12.17
  next: 15.0.0-rc.1
  "@vercel/functions": 1.4.2
