export enum TaskType {
  MAKE_A_SWAP = 'MAKE_A_SWAP',
  HOLD_A_TOKEN = 'HOLD_A_TOKEN',
  ADD_LIQUIDITY = 'ADD_LIQUIDITY',
  PARTICIPATE_LOTTERY = 'PARTICIPATE_LOTTERY',
  VISIT_BLOG_POST = 'VISIT_BLOG_POST',
  MAKE_A_PREDICTION = 'MAKE_A_PREDICTION',
  // Social
  X_LIKE_POST = 'X_LIKE_POST',
  X_FOLLOW_ACCOUNT = 'X_FOLLOW_ACCOUNT',
  X_REPOST_POST = 'X_REPOST_POST',
  TELEGRAM_JOIN_GROUP = 'TELEGRAM_JOIN_GROUP',
  DISCORD_JOIN_SERVER = 'DISCORD_JOIN_SERVER',

  YOUTUBE_SUBSCRIBE = 'YOUTUBE_SUBSCRIBE',
  IG_LIKE_POST = 'IG_LIKE_POST',
  IG_COMMENT_POST = 'IG_COMMENT_POST',
  IG_FOLLOW_ACCOUNT = 'IG_FOLLOW_ACCOUNT',
}

export const SUPPORT_ADD_TASK = [
  TaskType.MAKE_A_SWAP,
  TaskType.HOLD_A_TOKEN,
  TaskType.ADD_LIQUIDITY,
  TaskType.VISIT_BLOG_POST,
  TaskType.X_LIKE_POST,
  TaskType.X_FOLLOW_ACCOUNT,
  TaskType.X_REPOST_POST,
  TaskType.TELEGRAM_JOIN_GROUP,
  TaskType.DISCORD_JOIN_SERVER,
  TaskType.MAKE_A_PREDICTION,
  // TaskType.PARTICIPATE_LOTTERY,
]

export enum CompletionStatus {
  ONGOING = 'ONGOING',
  FINISHED = 'FINISHED',
  DRAFTED = 'DRAFTED',
  SCHEDULED = 'SCHEDULED',
  PENDING_REWARD = 'PENDING_REWARD',
}

export enum CompletionStatusIndex {
  ONGOING = 0,
  SCHEDULED = 1,
  FINISHED = 2,
  DRAFTED = 3,
}

export enum RewardType {
  TOKEN = 'TOKEN',
  NFT = 'NFT',
  POINTS = 'POINTS',
}
