export enum TaskType {
  MAKE_A_SWAP = 'MAKE_A_SWAP',
  HOLD_A_TOKEN = 'HOLD_A_TOKEN',
  ADD_LIQUIDITY = 'ADD_LIQUIDITY',
  PARTICIPATE_LOTTERY = 'PARTICIPATE_LOTTERY',
  ADD_BLOG_POST = 'ADD_BLOG_POST',
  MAKE_PREDICTION = 'MAKE_PREDICTION',
  // Social
  X_LINK_POST = 'X_LINK_POST',
  X_FOLLOW_ACCOUNT = 'X_FOLLOW_ACCOUNT',
  X_REPOST_POST = 'X_REPOST_POST',
  TELEGRAM_JOIN_GROUP = 'TELEGRAM_JOIN_GROUP',
  DISCORD_JOIN_SERVICE = 'DISCORD_JOIN_SERVICE',

  YOUTUBE_SUBSCRIBE = 'YOUTUBE_SUBSCRIBE',
  IG_LIKE_POST = 'IG_LIKE_POST',
  IG_COMMENT_POST = 'IG_COMMENT_POST',
  IG_FOLLOW_ACCOUNT = 'IG_FOLLOW_ACCOUNT',
}

export const SUPPORT_ADD_TASK = [
  TaskType.MAKE_A_SWAP,
  TaskType.HOLD_A_TOKEN,
  TaskType.ADD_BLOG_POST,
  TaskType.X_LINK_POST,
  TaskType.X_FOLLOW_ACCOUNT,
  TaskType.X_REPOST_POST,
  TaskType.TELEGRAM_JOIN_GROUP,
  TaskType.DISCORD_JOIN_SERVICE,
]

export enum CompletionStatus {
  ONGOING = 'ONGOING',
  CLAIMABLE = 'CLAIMABLE',
  FINISHED = 'FINISHED',
}

export enum RewardType {
  TOKEN = 'TOKEN',
  NFT = 'NFT',
  POINTS = 'POINTS',
}
