export const ASSET_CDN = 'https://assets.pancakeswap.finance'
export const API_NFT = 'https://nft.pancakeswap.com/api/v1'
export const API_PROFILE = 'https://profile.pancakeswap.com'
export const GRAPH_API_NFTMARKET = 'https://api.thegraph.com/subgraphs/name/pancakeswap/nft-market'
export const CELER_API = 'https://api.celerscan.com/scan'
export const GRAPH_API_PROFILE = 'https://api.thegraph.com/subgraphs/name/pancakeswap/profile'
export const GAMIFICATION_API = 'http://159.65.4.211:80/api'
export const GAMIFICATION_PUBLIC_API = 'https://sea-turtle-app-b4e6d.ondigitalocean.app/api'
