export const calcGaugesVotingABI = [
  {
    inputs: [],
    name: 'gaugeVotingAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_gaugeAddr', type: 'address' },
      { internalType: 'uint256', name: '_chainId', type: 'uint256' },
      { internalType: 'bool', name: '_inCap', type: 'bool' },
    ],
    name: 'getGaugeRelativeWeight',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gaugeId', type: 'uint256' },
      { internalType: 'bool', name: '_inCap', type: 'bool' },
    ],
    name: 'getGaugeRelativeWeightById',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_gaugeAddr', type: 'address' },
      { internalType: 'uint256', name: '_chainId', type: 'uint256' },
      { internalType: 'bool', name: '_inCap', type: 'bool' },
    ],
    name: 'getGaugeWeight',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_gaugeId', type: 'uint256' }],
    name: 'getGaugeWeightDetails',
    outputs: [
      { internalType: 'uint256', name: 'gaugeWeight', type: 'uint256' },
      { internalType: 'uint256', name: 'gaugeTotalWeight', type: 'uint256' },
      { internalType: 'uint256', name: 'gaugeRawPercent', type: 'uint256' },
      { internalType: 'uint256', name: 'gaugeCappedPercent', type: 'uint256' },
      { internalType: 'uint256', name: 'gaugeInCapWeight', type: 'uint256' },
      { internalType: 'uint256', name: 'gaugeTotalFinalWeights', type: 'uint256' },
      { internalType: 'uint256', name: 'gaugeFinalPercent', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_gaugeAddr', type: 'address' },
      { internalType: 'uint256', name: '_chainId', type: 'uint256' },
      { internalType: 'bool', name: '_inCap', type: 'bool' },
      { internalType: 'uint256', name: '_gaugeTotalWeight', type: 'uint256' },
      { internalType: 'uint256', name: '_gaugeTotalCappedPercent', type: 'uint256' },
      { internalType: 'uint256', name: '_gaugeTotalFinalWeights', type: 'uint256' },
    ],
    name: 'getGaugeWeightMass',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gaugeId', type: 'uint256' },
      { internalType: 'bool', name: '_inCap', type: 'bool' },
    ],
    name: 'getGaugeWeightbyId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRawTotalGaugeWeight',
    outputs: [{ internalType: 'uint256', name: 'gaugeTotalWeight', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTotalCappedPercent',
    outputs: [{ internalType: 'uint256', name: 'gaugeTotalCappedPercent', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTotalFinalWeights',
    outputs: [{ internalType: 'uint256', name: 'gaugeTotalFinalWeights', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: '_inCap', type: 'bool' }],
    name: 'getTotalWeight',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: '_inCap', type: 'bool' }],
    name: 'massGetGaugeWeight',
    outputs: [{ internalType: 'uint256[]', name: 'result', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
