name: 'Install Dependencies'
description: 'Install dependencies with pnpm'

run:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - uses: pnpm/action-setup@v4
      with:
        version: 9.8.0

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.0'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install --ignore-scripts
