name: 💡 Feature Request
description: Share your amazing ideas!
title: '[Feature Request] <title>'
labels: [Feature Request, Triage]
assignees:
  - Chef-Chungus
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you requested.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      - label: Is your feature request related to a problem you are facing?
      - description: Enter a clear and concise description of what the problem is 
      - placeholder: I'm always frustrated when [...]
      - required: true
  - type: textarea
    attributes:
      - label: Describe the solution you'd like
      - description: A clear and concise description of what you want to happen.
      - required: true
  - type: textarea
    attributes:
      - label: How does this feature benefit PancakeSwap users and CAKE holders?
      - description: Explain how this feature will be beneficial for the PancakeSwap community and ecosystem.
      - required: true
  - type: textarea
    attributes:
      - label: Anything else? 
      - description: Add any other context or screenshots about the feature request here.
      - required: false