export const UPDATE_ACCOUNT = "updateAccount"
export const UPDATE_ZOMBIE_ALLOWANCE = "updateZombieAllowance"
export const UPDATE_ZOMBIE_TOTAL_SUPPLY = "updateZombieTotalSupply"
export const UPDATE_ZOMBIE_BALANCE = "updateZombieBalance"
export const UPDATE_BNB_PRICE_USD = "updateBnbPriceUsd"
export const UPDATE_ZOMBIE_PRICE_BNB = "updateZombiePriceBnb"
export const UPDATE_TOMB = "updateTomb"
export const UPDATE_GRAVE_POOL_INFO = "updateGravePoolInfo"
export const UPDATE_GRAVE_USER_INFO = "updateGraveUserInfo"
export const UPDATE_DR_FRANKENSTEIN_ZOMBIE_BALANCE = "updateDrFrankensteinZombieBalance"

