export const UPDATE_ACCOUNT = "updateAccount"
export const UPDATE_ZOMBIE_ALLOWANCE = "updateZombieAllowance"
export const UPDATE_ZOMBIE_TOTAL_SUPPLY = "updateZombieTotalSupply"
export const UPDATE_ZOMBIE_BALANCE = "updateZombieBalance"
export const UPDATE_BNB_PRICE_USD = "updateBnbPriceUsd"
export const UPDATE_ZOMBIE_PRICE_BNB = "updateZombiePriceBnb"
export const UPDATE_GRAVE_POOL_INFO = "updateGravePoolInfo"
export const UPDATE_GRAVE_USER_INFO = "updateGraveUserInfo"
export const UPDATE_TOMB_USER_INFO = "updateTombUserInfo"
export const UPDATE_TOMB_POOL_INFO = "updateTombPoolInfo"
export const UPDATE_SPAWNING_POOL_INFO = "updateSpawningPoolInfo"
export const UPDATE_SPAWNING_POOL_USER_INFO = "updateSpawningPoolUserInfo"
export const UPDATE_DR_FRANKENSTEIN_ZOMBIE_BALANCE = "updateDrFrankensteinZombieBalance"
export const UPDATE_NFT_TOTAL_SUPPLY = "updateNftTotalSupply"
export const UPDATE_AUCTION_INFO = "updateAuctionInfo"
export const UPDATE_AUCTION_USER_INFO = "updateAuctionUserInfo"
export const UPDATE_NFT_USER_INFO = "updateNftUserInfo"

