// eslint-disable-next-line import/prefer-default-export
import tokens from '../config/constants/tokens'
import artists from '../config/constants/artists'
import { BIG_ZERO } from '../utils/bigNumber'
import { Grave } from './types'

const graves: Grave[] = [
  {
    pid: 22,
    name: 'RugZombie Common',
    subtitle: 'Basic Zombie',
    path: 'images/rugZombie/BasicZombie.gif',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '7 days',
    rug: tokens.zmbe,
    artist: artists.RugZombie,
    stakingToken: '0x1D4CA2139E942b2EA9d7B40AF3805967242b7525',
    pcsVersion: 'v2',
    liquidityDetails: '',
    isEnding: false,
    isClosed: false,
    rarity: "Common",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 0,
    name: 'RugZombie Common (Legacy)',
    subtitle: 'Basic Zombie',
    path: 'images/rugZombie/BasicZombie.gif',
    type: 'image',
    withdrawalCooldown: '30 days',
    nftRevivalTime: '30 days',
    rug: tokens.none,
    artist: artists.RugZombie,
    stakingToken: '',
    pcsVersion: 'v2',
    liquidityDetails: '',
    isClosed: true,
    isRetired: true,
    rarity: "Common",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 23,
    name: 'RugZombie Uncommon',
    subtitle: 'Zombie Horde',
    path: 'images/rugZombie/Zombie Multiplier.png',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '14 days',
    rug: tokens.basicZmbe,
    artist: artists.RugZombie,
    stakingToken: '0x5E15E3431d2037d3Ce20238d8fF45faF551aD6b2',
    pcsVersion: 'none',
    liquidityDetails: 'None! You must earn the Basic Zombie NFT from the RugZombie Common Grave to gain access.',
    requiresNft: true,
    requiredNftPath: 'images/rugZombie/BasicZombie.gif',
    nftConverterPid: 0,
    graveNftToken: "0x22e42D9425b55FD2262bfF72a316bb052DDb2a77",
    nft: "Basic Zombie",
    rarity: "Uncommon",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 24,
    name: 'RugZombie Rare',
    subtitle: 'Zombie Multiplexer',
    path: 'https://ipfs.io/ipfs/Qmdi7wTt8iF62ay8foD7nqP5F7qSB9YGaYgY3NL1URA5Cw',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.horde,
    artist: artists.RugZombie,
    stakingToken: '0xF4b4460AD6Ebb969BF26a61298D2087404610a11',
    pcsVersion: 'none',
    liquidityDetails: 'None! You must earn the Zombie Horde NFT from the RugZombie Uncommon Grave to gain access.',
    requiresNft: true,
    requiredNftPath: 'images/rugZombie/Zombie Multiplier.png',
    nftConverterPid: 1,
    graveNftToken: "0xE30043524ADb329169b11eDfe833a9beDd4D2A11",
    nft: "Zombie Horde",
    rarity: "Rare",
    isNew: true,
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 25,
    name: 'Pantherswap Legendary',
    subtitle: 'The Killmonger',
    path: "images/rugZombie/The Killmonger min.jpeg",
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.panther,
    artist: artists.eyes_of_lamia,
    stakingToken: '0x1D4CA2139E942b2EA9d7B40AF3805967242b7525',
    pcsVersion: 'v2',
    liquidityDetails: '',
    isEnding: false,
    isFeatured: true,
    isClosed: false,
    rarity: "Legendary",
    startingDate: 1631290500,
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 19,
    name: 'Emperor Token Rare',
    subtitle: 'Young Fool',
    path: 'https://storage.googleapis.com/rug-zombie/Young%20Fool.jpeg',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.zmpr,
    artist: artists.jussjoshinduh,
    stakingToken: '0x62debcB9f311a170BfbDA089465085DA551B42d2',
    pcsVersion: 'none',
    liquidityDetails: 'None! The ZMPR token was airdropped to EMPR holders so you will have to ask around the telegram.',
    isEnding: false,
    isFeatured: true,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 21,
    name: 'Hyrule Swap Rare',
    subtitle: 'GlitchLink',
    path: 'https://storage.googleapis.com/rug-zombie/GlitchLink.webm',
    type: 'video',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.grupee,
    artist: artists.none,
    stakingToken: '0x28E0c9aD40b658feDF239C442D2773E9dAb9a4f2',
    pcsVersion: 'Apeswap',
    liquidityDetails: '',
    isNew: true,
    isEnding: false,
    isFeatured: true,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 20,
    name: 'Hyrule Swap Uncommon',
    subtitle: 'Rugian Shield',
    path: 'https://storage.googleapis.com/rug-zombie/Rugian%20Shield.png',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '14 days',
    rug: tokens.rupee,
    artist: artists.none,
    stakingToken: '0xF83be0fb848CC0907858Db8B3f5CF88580c0C70e',
    pcsVersion: 'Apeswap',
    liquidityDetails: '',
    isNew: true,
    isEnding: false,
    isFeatured: true,
    rarity: "Uncommon",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 1,
    name: 'VikingSwap Rare',
    subtitle: 'Viking Brains',
    path: 'images/rugZombie/VikingBrains.jpeg',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.viking,
    artist: artists.TheLeap3d,
    stakingToken: '0x909e59fFFcF1481Df184831eEea6680Cd437A340',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    isFeatured: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 2,
    name: 'MonsterSlayer Rare',
    subtitle: 'ZombieSlayer',
    path: 'images/rugZombie/ZombieSlayer.gif',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.msc,
    artist: artists.ZomBaes,
    stakingToken: '0xD4Ced04fB7129CDB43ffef1cf3DE3Ac701c6cE33',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 18,
    name: 'Thunderswap Rare',
    subtitle: 'Electric Zombie',
    path: 'images/rugZombie/Electric Zombie.png',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.tndr,
    artist: artists.TheLeap3d,
    stakingToken: '0xdab566c6E63b06D641ABdCCaC4c6941C645812BD',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    isFeatured: true,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 12,
    name: 'Autoshark Legendary',
    subtitle: 'Chompers',
    path: 'images/rugZombie/Chompers.webm',
    type: 'video',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.zshark,
    artist: artists.deadtunnelrat,
    stakingToken: '0x8fab22cB7C58b193Fd498ed0EF3B574d70E4f759',
    pcsVersion: 'none',
    liquidityDetails: 'None! This grave is exclusive for victims of the flash loan attack on autoshark.',
    isNew: false,
    isEnding: true,
    isClosed: true,
    isRetired: true,
    endDate: 1630900799,
    latestEntryDate: "Aug. 4th, 2021",
    rarity: "Legendary",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 15,
    name: 'RUGBIDEN Rare',
    subtitle: 'Zombiden',
    path: 'https://storage.googleapis.com/rug-zombie/RUGBIDEN.webm',
    type: 'video',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.rugbiden,
    artist: artists.ZomBaes,
    stakingToken: '0xF462EFC96E47d6Fa2b03e1f8757aA38FeAa9aC3d',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 16,
    name: 'Burger Swap Rare',
    subtitle: 'Zomburger',
    path: 'images/rugZombie/Zomburger.jpeg',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.burger,
    artist: artists.jussjoshinduh,
    stakingToken: '0x6351b17cecb2A143c72Af9AF8075667Aa6A139F6',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 13,
    name: 'The US Dollar Rare',
    subtitle: 'DeadDollar',
    path: 'images/rugZombie/DeadDollar.png',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.busd,
    artist: artists.TheLeap3d,
    stakingToken: '0xB95B670b9Cd0Da6D9C65dab68c41c394633410b4',
    pcsVersion: 'v2',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 3,
    name: 'Defi100 Rare',
    subtitle: 'Zombie100',
    path: 'images/rugZombie/Zombie100.gif',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.d100,
    artist: artists.ZomBaes,
    stakingToken: '0xfB33d25b41F1b0fa95AEa52486C3F05f2aDEE396',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 10,
    name: 'Merlin Lab Rare',
    subtitle: 'My name is MERL',
    path: 'images/rugZombie/My Name Is MERL.png',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.merl,
    artist: artists.none,
    pcsVersion: 'v2',
    stakingToken: '0xD1e00C08E938B808F2d65dd108aE50948a9Ca1b4',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 4,
    name: 'Fairmoon Rare',
    subtitle: 'Raremoon',
    path: 'images/rugZombie/Raremoon.jpeg',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '30 days',
    rug: tokens.fairmoon,
    artist: artists.TheLeap3d,
    stakingToken: '0x26dF9e0fbd5624941767516BbF218554CfA3A110',
    pcsVersion: 'v1',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Rare",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 14,
    name: 'Uranium Finance Uncommon',
    subtitle: 'The Rad Chad',
    path: 'images/rugZombie/The Rad Chad.png',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '14 days',
    rug: tokens.u92,
    artist: artists.jussjoshinduh,
    pcsVersion: 'v2',
    stakingToken: '0xB0CEA8C1AaA7a62de12BC5c15f0de1694ED9fab7',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Uncommon",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 5,
    name: 'Fairmoon Uncommon',
    subtitle: 'Zombie on the Moon',
    path: 'images/rugZombie/FairmoonUncommon.webm',
    type: 'video',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '14 days',
    rug: tokens.fairmoon,
    artist: artists.none,
    pcsVersion: 'v1',
    stakingToken: '0x645ad805c464133Eba5c4152Ce14547a01F821f7',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Uncommon",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 6,
    name: 'Fairmoon Common',
    subtitle: 'Fairmoon Common',
    path: 'images/rugZombie/FairmoonCommon.webm',
    type: 'video',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '7 days',
    rug: tokens.fairmoon,
    artist: artists.none,
    pcsVersion: 'v1',
    stakingToken: '0x02F6DE73919aE9d43A1E0520dBCBF81bCda5B514',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Common",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 7,
    name: 'Gorilla Yield Common',
    subtitle: 'Gorilla Yield Common',
    path: 'images/rugZombie/yApeCommon.jpeg',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '7 days',
    rug: tokens.yape,
    artist: artists.none,
    pcsVersion: 'v1',
    stakingToken: '0x9EbD27Bd3957F13f8E7fef988E96B8EE1998bc80',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Common",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 8,
    name: 'Dragon Farm Finance Common',
    subtitle: 'Dragon Farm Finance Common',
    path: 'images/rugZombie/CommonDragonFarmFinance.webm',
    type: 'video',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '7 days',
    rug: tokens.dragon,
    artist: artists.none,
    pcsVersion: 'v1',
    stakingToken: '0x634A554d2FF1609d50740240140B452dF60D035c',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    rarity: "Common",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
  {
    pid: 9,
    name: 'yPanda Common',
    subtitle: 'yPanda Common',
    path: 'images/rugZombie/yPandaCommon.jpeg',
    type: 'image',
    withdrawalCooldown: '3 days',
    nftRevivalTime: '7 days',
    rug: tokens.ypanda,
    artist: artists.none,
    pcsVersion: 'v1',
    stakingToken: '0xFceB2967AB8EcC29589E9232f78f8441832d2aD6',
    liquidityDetails: '',
    isNew: false,
    isEnding: false,
    isClosed: false,
    rarity: "Common",
    userInfo: {
      paidUnlockFee: false,
      tokenWithdrawalDate: 0,
      nftRevivalDate: 0,
      rugDeposited: BIG_ZERO,
      amount: BIG_ZERO,
      pendingZombie: BIG_ZERO,
    },
    poolInfo: {
      lpToken: undefined,
      unlockFee: BIG_ZERO,
      minimumStake: BIG_ZERO,
      totalStakingTokenStaked: BIG_ZERO,
      withdrawCooldown: 0,
      nftRevivalTime: 0,
      allocPoint: 0
    },
  },
]

export default graves
