export const swETHAbi = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'AddressAlreadyInWhitelist',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'AddressMissingFromWhitelist',
    type: 'error',
  },
  { inputs: [], name: 'CannotBeZeroAddress', type: 'error' },
  { inputs: [], name: 'CannotBurnZeroSwETH', type: 'error' },
  { inputs: [], name: 'CannotReferSelf', type: 'error' },
  { inputs: [], name: 'CannotRepriceWithZeroSwETHSupply', type: 'error' },
  { inputs: [], name: 'CoreMethodsPaused', type: 'error' },
  { inputs: [], name: 'InvalidETHDeposit', type: 'error' },
  { inputs: [], name: 'InvalidMethodCall', type: 'error' },
  { inputs: [], name: 'InvalidPreRewardETHReserves', type: 'error' },
  { inputs: [], name: 'NoTokensToWithdraw', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'remainingTime', type: 'uint256' }],
    name: 'NotEnoughTimeElapsedForReprice',
    type: 'error',
  },
  { inputs: [], name: 'NotInWhitelist', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'x', type: 'uint256' },
      { internalType: 'uint256', name: 'y', type: 'uint256' },
    ],
    name: 'PRBMath_MulDiv18_Overflow',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'x', type: 'uint256' },
      { internalType: 'uint256', name: 'y', type: 'uint256' },
      { internalType: 'uint256', name: 'denominator', type: 'uint256' },
    ],
    name: 'PRBMath_MulDiv_Overflow',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'repriceDiff', type: 'uint256' },
      { internalType: 'uint256', name: 'maximumRepriceDiff', type: 'uint256' },
    ],
    name: 'RepriceDifferenceTooLarge',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'repriceswETHDiff', type: 'uint256' },
      { internalType: 'uint256', name: 'maximumswETHRepriceDiff', type: 'uint256' },
    ],
    name: 'RepriceswETHDifferenceTooLarge',
    type: 'error',
  },
  { inputs: [], name: 'RewardPercentageTotalOverflow', type: 'error' },
  { inputs: [], name: 'WhitelistAlreadyDisabled', type: 'error' },
  { inputs: [], name: 'WhitelistAlreadyEnabled', type: 'error' },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: '_address', type: 'address' }],
    name: 'AddedToWhitelist',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'spender', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'swETHMinted', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newTotalETHDeposited', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'referral', type: 'address' },
    ],
    name: 'ETHDepositReceived',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'swETHBurned', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'ethReturned', type: 'uint256' },
    ],
    name: 'ETHWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: '_oldMaximumRepriceDifferencePercentage', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: '_newMaximumRepriceDifferencePercentage', type: 'uint256' },
    ],
    name: 'MaximumRepriceDifferencePercentageUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: '_oldMaximumRepriceswETHDifferencePercentage', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: '_newMaximumRepriceswETHDifferencePercentage', type: 'uint256' },
    ],
    name: 'MaximumRepriceswETHDifferencePercentageUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: '_oldMinimumRepriceTime', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: '_newMinimumRepriceTime', type: 'uint256' },
    ],
    name: 'MinimumRepriceTimeUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'oldPercentage', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newPercentage', type: 'uint256' },
    ],
    name: 'NodeOperatorRewardPercentageUpdate',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: '_address', type: 'address' }],
    name: 'RemovedFromWhitelist',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'newEthReserves', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newSwETHToETHRate', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'nodeOperatorRewards', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'swellTreasuryRewards', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'totalETHDeposited', type: 'uint256' },
    ],
    name: 'Reprice',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'oldPercentage', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newPercentage', type: 'uint256' },
    ],
    name: 'SwellTreasuryRewardPercentageUpdate',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'WhitelistDisabled', type: 'event' },
  { anonymous: false, inputs: [], name: 'WhitelistEnabled', type: 'event' },
  { stateMutability: 'nonpayable', type: 'fallback' },
  {
    inputs: [],
    name: 'AccessControlManager',
    outputs: [{ internalType: 'contract IAccessControlManager', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'addToWhitelist',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address[]', name: '_addresses', type: 'address[]' }],
    name: 'batchAddToWhitelist',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address[]', name: '_addresses', type: 'address[]' }],
    name: 'batchRemoveFromWhitelist',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'burn',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'subtractedValue', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'deposit', outputs: [], stateMutability: 'payable', type: 'function' },
  {
    inputs: [{ internalType: 'address', name: 'referral', type: 'address' }],
    name: 'depositWithReferral',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  { inputs: [], name: 'disableWhitelist', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'enableWhitelist', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'ethToSwETHRate',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRate',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'addedValue', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'contract IAccessControlManager', name: '_accessControlManager', type: 'address' }],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lastRepriceETHReserves',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lastRepriceUNIX',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maximumRepriceDifferencePercentage',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maximumRepriceswETHDifferencePercentage',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minimumRepriceTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nodeOperatorRewardPercentage',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'removeFromWhitelist',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_preRewardETHReserves', type: 'uint256' },
      { internalType: 'uint256', name: '_newETHRewards', type: 'uint256' },
      { internalType: 'uint256', name: '_swETHTotalSupply', type: 'uint256' },
    ],
    name: 'reprice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_maximumRepriceDifferencePercentage', type: 'uint256' }],
    name: 'setMaximumRepriceDifferencePercentage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_maximumRepriceswETHDifferencePercentage', type: 'uint256' }],
    name: 'setMaximumRepriceswETHDifferencePercentage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_minimumRepriceTime', type: 'uint256' }],
    name: 'setMinimumRepriceTime',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_newNodeOperatorRewardPercentage', type: 'uint256' }],
    name: 'setNodeOperatorRewardPercentage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_newSwellTreasuryRewardPercentage', type: 'uint256' }],
    name: 'setSwellTreasuryRewardPercentage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'swETHToETHRate',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'swellTreasuryRewardPercentage',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalETHDeposited',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'whitelistEnabled',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'whitelistedAddresses',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'contract IERC20', name: '_token', type: 'address' }],
    name: 'withdrawERC20',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
