import { ethereumTokens } from '@pancakeswap/tokens'
import { FeeAmount } from '@pancakeswap/v3-sdk'
import { Strategy, VaultConfig } from '../../types'
import { MANAGER } from '../managers'

export const vaults: VaultConfig[] = [
  {
    id: 1,
    idByManager: 1,
    name: 'RANGE',
    address: '0x589e8bC919fF18fbF62c7C3d8E3fD86ecD7549C3',
    adapterAddress: '0x4b2fC4DdB3D5875bF6C78a5dA17cb17d73E7acb4',
    currencyA: ethereumTokens.rETH,
    currencyB: ethereumTokens.weth,
    earningToken: ethereumTokens.cake,
    feeTier: FeeAmount.LOW,
    strategy: Strategy.PEGGED,
    manager: MANAGER.RANGE,
    isSingleDepositToken: false,
    allowDepositToken0: true,
    allowDepositToken1: true,
    managerInfoUrl: 'https://www.rangeprotocol.com/',
    strategyInfoUrl: 'https://range-protocol.gitbook.io/range-protocol/amm-vaults/strategy-details',
    learnMoreAboutUrl: 'https://range-protocol.gitbook.io/range-protocol/amm-vaults/strategy-details',
  },
  {
    id: 2,
    idByManager: 2,
    name: 'RANGE',
    address: '0xBfaa05CA3078912344491926Ff81F6a75AEFea8b',
    adapterAddress: '0xc59B81e93F62ea7E2Bb812ED03e1364D4c709Dfb',
    currencyA: ethereumTokens.usdc,
    currencyB: ethereumTokens.usdt,
    earningToken: ethereumTokens.cake,
    feeTier: FeeAmount.LOWEST,
    strategy: Strategy.PEGGED,
    manager: MANAGER.RANGE,
    isSingleDepositToken: false,
    allowDepositToken0: true,
    allowDepositToken1: true,
    managerInfoUrl: 'https://www.rangeprotocol.com/',
    strategyInfoUrl: 'https://range-protocol.gitbook.io/range-protocol/amm-vaults/strategy-details',
    learnMoreAboutUrl: 'https://range-protocol.gitbook.io/range-protocol/amm-vaults/strategy-details',
  },
  {
    id: 3,
    idByManager: 3,
    name: 'RANGE',
    address: '0xBcbb1928a72423505f5B479CEd487DA048911669',
    adapterAddress: '0x5B3184A534552cbc6Fe0f571f6a56908094aD2d8',
    currencyA: ethereumTokens.weth,
    currencyB: ethereumTokens.usdt,
    earningToken: ethereumTokens.cake,
    feeTier: FeeAmount.LOW,
    strategy: Strategy.PASSIVE,
    manager: MANAGER.RANGE,
    isSingleDepositToken: false,
    allowDepositToken0: true,
    allowDepositToken1: true,
    managerInfoUrl: 'https://www.rangeprotocol.com/',
    strategyInfoUrl: 'https://range-protocol.gitbook.io/range-protocol/amm-vaults/strategy-details',
    learnMoreAboutUrl: 'https://range-protocol.gitbook.io/range-protocol/amm-vaults/strategy-details',
  },
]
