import { polygonZkEvmTokens } from '@pancakeswap/tokens'
import { FeeAmount } from '@pancakeswap/v3-sdk'
import { Strategy, VaultConfig } from '../../types'
import { MANAGER } from '../managers'

export const vaults: VaultConfig[] = [
  {
    id: 3,
    idByManager: 3,
    name: 'BRIL',
    manager: MANAGER.BRIL,
    bCakeWrapperAddress: '0x6ef151413502046479e6Cac5378AD737D09fe61D',
    address: '0x6ef151413502046479e6Cac5378AD737D09fe61D',
    adapterAddress: '0x4403025D25DC1768B87224FDDfe96394Caa35c58',
    currencyA: polygonZkEvmTokens.weth,
    currencyB: polygonZkEvmTokens.rsETH,
    earningToken: polygonZkEvmTokens.matic,
    feeTier: FeeAmount.LOW,
    strategy: Strategy.YIELD_IQ,
    isSingleDepositToken: true,
    allowDepositToken0: true,
    allowDepositToken1: false,
    managerInfoUrl: 'https://www.bril.finance/',
    strategyInfoUrl: 'https://docs.bril.finance/yield-iq/overview',
    learnMoreAboutUrl: 'https://docs.bril.finance/bril-finance/introduction',
    priceFromV3FarmPid: 10,
  },
  {
    id: 2,
    idByManager: 2,
    name: 'BRIL',
    manager: MANAGER.BRIL,
    bCakeWrapperAddress: '0x2C3F0aD2fa20aDedeD322Ec2d2cb1CA1656b176d',
    address: '0x2C3F0aD2fa20aDedeD322Ec2d2cb1CA1656b176d',
    adapterAddress: '0xd4358AE4B833c8fd39E5497A3EdC7fF430a57B8c',
    currencyA: polygonZkEvmTokens.weth,
    currencyB: polygonZkEvmTokens.reth,
    earningToken: polygonZkEvmTokens.matic,
    feeTier: FeeAmount.LOW,
    strategy: Strategy.YIELD_IQ,
    isSingleDepositToken: true,
    allowDepositToken0: true,
    allowDepositToken1: false,
    managerInfoUrl: 'https://www.bril.finance/',
    strategyInfoUrl: 'https://docs.bril.finance/yield-iq/overview',
    learnMoreAboutUrl: 'https://docs.bril.finance/bril-finance/introduction',
    priceFromV3FarmPid: 13,
  },
  {
    id: 1,
    idByManager: 1,
    name: 'BRIL',
    manager: MANAGER.BRIL,
    bCakeWrapperAddress: '0x308Cb883074b270700096a5931BfFF81701b44f2',
    address: '0x308Cb883074b270700096a5931BfFF81701b44f2',
    adapterAddress: '0xc44940c05aA4a24a637EaC3A6be1bc763a24Ef5d',
    currencyA: polygonZkEvmTokens.weth,
    currencyB: polygonZkEvmTokens.wstETH,
    earningToken: polygonZkEvmTokens.matic,
    feeTier: FeeAmount.LOW,
    strategy: Strategy.YIELD_IQ,
    isSingleDepositToken: true,
    allowDepositToken0: true,
    allowDepositToken1: false,
    managerInfoUrl: 'https://www.bril.finance/',
    strategyInfoUrl: 'https://docs.bril.finance/yield-iq/overview',
    learnMoreAboutUrl: 'https://docs.bril.finance/bril-finance/introduction',
    priceFromV3FarmPid: 12,
  },
]
