import { ChainId } from '@pancakeswap/chains'
import { arbitrumTokens } from '@pancakeswap/tokens'
import { FeeAmount, Pool } from '@pancakeswap/v3-sdk'
import { defineFarmV3ConfigsFromUniversalFarm } from '../defineFarmV3Configs'
import { Protocol, SerializedFarmConfig, UniversalFarmConfig, UniversalFarmConfigV3 } from '../types'

const pinnedFarmConfig: UniversalFarmConfig[] = [
  {
    pid: 43,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 42,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 2,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.usdt, FeeAmount.LOW),
  },
  {
    pid: 1,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.usdc, FeeAmount.LOW),
  },
]

export const arbFarmConfig: UniversalFarmConfig[] = [
  ...pinnedFarmConfig,
  {
    pid: 93,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.egp, arbitrumTokens.weth, FeeAmount.HIGH),
    token0: arbitrumTokens.egp,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.HIGH,
  },
  {
    pid: 92,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.usdplus, arbitrumTokens.usdt, FeeAmount.LOWEST),
    token0: arbitrumTokens.usdplus,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 91,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.gusdc, FeeAmount.LOWEST),
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.gusdc,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 90,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.pendle, arbitrumTokens.weth, FeeAmount.LOW),
    token0: arbitrumTokens.pendle,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 89,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.seed, FeeAmount.MEDIUM),
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.seed,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 88,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.usde, arbitrumTokens.usdc, FeeAmount.LOWEST),
    token0: arbitrumTokens.usde,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 87,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.solvbtcbbn, arbitrumTokens.solvbtc, FeeAmount.LOW),
    token0: arbitrumTokens.solvbtcbbn,
    token1: arbitrumTokens.solvbtc,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 86,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.solvbtc, FeeAmount.LOW),
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.solvbtc,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 85,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.dai, arbitrumTokens.usdt, FeeAmount.LOWEST),
    token0: arbitrumTokens.dai,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 84,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.wstETH, arbitrumTokens.mstETH, FeeAmount.LOW),
    token0: arbitrumTokens.wstETH,
    token1: arbitrumTokens.mstETH,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 83,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.grt, FeeAmount.LOW),
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.grt,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 82,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.ethPlus, arbitrumTokens.weth, FeeAmount.LOWEST),
    token0: arbitrumTokens.ethPlus,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 81,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.tap, arbitrumTokens.weth, FeeAmount.MEDIUM),
    token0: arbitrumTokens.tap,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 80,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.usde, arbitrumTokens.usdt, FeeAmount.LOWEST),
    token0: arbitrumTokens.usde,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 79,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.pendle, arbitrumTokens.weth, FeeAmount.LOWEST),
    token0: arbitrumTokens.pendle,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 78,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.zro, arbitrumTokens.weth, FeeAmount.LOW),
    token0: arbitrumTokens.zro,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 77,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.wstETH, arbitrumTokens.usdce, FeeAmount.LOWEST),
    token0: arbitrumTokens.wstETH,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 76,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.usdce, FeeAmount.LOWEST),
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 75,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.usdt, FeeAmount.LOWEST),
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 74,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.sqd,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(arbitrumTokens.sqd, arbitrumTokens.weth, FeeAmount.HIGH),
  },
  {
    pid: 73,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.solvBTC,
    token1: arbitrumTokens.solvBTCena,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.solvBTC, arbitrumTokens.solvBTCena, FeeAmount.LOW),
  },
  {
    pid: 72,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.zro,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.zro, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 71,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.fusdc,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.fusdc, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 70,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.usdce, FeeAmount.LOWEST),
  },
  {
    pid: 69,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 68,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdt,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdt, arbitrumTokens.usdce, FeeAmount.LOWEST),
  },
  {
    pid: 67,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.usdce, FeeAmount.LOWEST),
  },
  {
    pid: 66,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.arb,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.arb, arbitrumTokens.usdce, FeeAmount.LOWEST),
  },
  {
    pid: 65,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.mim,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.mim, FeeAmount.LOWEST),
  },
  {
    pid: 64,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.woo,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.woo, FeeAmount.LOW),
  },
  {
    pid: 63,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.tia,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.tia, FeeAmount.MEDIUM),
  },
  {
    pid: 62,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.magic,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.magic, arbitrumTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 61,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdv,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.usdv, arbitrumTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 60,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.fly,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.fly, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 59,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.axlUSDC,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.axlUSDC, arbitrumTokens.usdce, FeeAmount.LOWEST),
  },
  {
    pid: 58,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weETH,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weETH, arbitrumTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 57,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.ezETH,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.ezETH, arbitrumTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 56,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.ethX,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.ethX, FeeAmount.LOWEST),
  },
  {
    pid: 55,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.rsETH,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.rsETH, arbitrumTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 54,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.grai,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.grai, FeeAmount.MEDIUM),
  },
  {
    pid: 53,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdv,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdv, arbitrumTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 52,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdv,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdv, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 51,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.usdplus, FeeAmount.LOWEST),
  },
  {
    pid: 50,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.arb,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.arb, arbitrumTokens.usdplus, FeeAmount.LOWEST),
  },
  {
    pid: 49,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.usdplus, FeeAmount.LOWEST),
  },
  {
    pid: 48,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.usdc, FeeAmount.LOW),
  },
  {
    pid: 47,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.arb,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.arb, arbitrumTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 46,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.arb,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.arb, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 45,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.arb,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.arb, FeeAmount.LOWEST),
  },
  {
    pid: 44,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 41,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdv,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdv, arbitrumTokens.usdplus, FeeAmount.LOWEST),
  },
  {
    pid: 40,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdtplus,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.usdtplus, arbitrumTokens.usdplus, FeeAmount.LOW),
  },
  {
    pid: 39,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.usdplus, FeeAmount.LOW),
  },
  {
    pid: 38,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 37,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.ovn,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(arbitrumTokens.ovn, arbitrumTokens.usdplus, FeeAmount.HIGH),
  },
  {
    pid: 36,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.ethplus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.ethplus, FeeAmount.LOWEST),
  },
  {
    pid: 35,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdplus,
    token1: arbitrumTokens.usdce,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdplus, arbitrumTokens.usdce, FeeAmount.LOWEST),
  },
  {
    pid: 34,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.ethplus,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.ethplus, arbitrumTokens.usdplus, FeeAmount.MEDIUM),
  },
  {
    pid: 33,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdtplus,
    token1: arbitrumTokens.usdplus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdtplus, arbitrumTokens.usdplus, FeeAmount.LOWEST),
  },
  {
    pid: 32,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.xai,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.xai, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 3,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.arb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.arb, FeeAmount.LOW),
  },
  {
    pid: 4,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 5,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.cake,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.cake, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 6,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.lvl,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.lvl, FeeAmount.MEDIUM),
  },
  {
    pid: 7,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.mgp,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.mgp, FeeAmount.MEDIUM),
  },
  {
    pid: 8,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.arb,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.arb, arbitrumTokens.usdc, FeeAmount.LOW),
  },
  {
    pid: 9,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.arb,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.arb, arbitrumTokens.usdt, FeeAmount.LOW),
  },
  {
    pid: 10,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.pendle,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.pendle, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 11,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.gmx,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.gmx, FeeAmount.MEDIUM),
  },
  {
    pid: 12,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.link,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.link, FeeAmount.MEDIUM),
  },
  {
    pid: 13,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.kuji,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.kuji, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 14,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.link,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.link, FeeAmount.MEDIUM),
  },
  {
    pid: 15,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.eqb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.eqb, FeeAmount.MEDIUM),
  },
  {
    pid: 16,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.axlUSDC,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.axlUSDC, FeeAmount.LOWEST),
  },
  {
    pid: 17,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.wbtc,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.wbtc, arbitrumTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 18,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.usdc,
    token1: arbitrumTokens.dai,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.usdc, arbitrumTokens.dai, FeeAmount.LOWEST),
  },
  {
    pid: 19,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.axlUSDC,
    token1: arbitrumTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.axlUSDC, arbitrumTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 20,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.stg,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.stg, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 21,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.stg,
    token1: arbitrumTokens.arb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.stg, arbitrumTokens.arb, FeeAmount.MEDIUM),
  },
  {
    pid: 22,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.stg,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.stg, arbitrumTokens.usdc, FeeAmount.MEDIUM),
  },
  {
    pid: 23,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.rdnt,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.rdnt, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 24,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.magic,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.magic, arbitrumTokens.weth, FeeAmount.MEDIUM),
  },
  {
    pid: 25,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.wstETH,
    token1: arbitrumTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.wstETH, arbitrumTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 26,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.rETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.rETH, FeeAmount.LOWEST),
  },
  {
    pid: 27,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.stEUR,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.stEUR, arbitrumTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 28,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.kuji,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.kuji, arbitrumTokens.usdc, FeeAmount.MEDIUM),
  },
  {
    pid: 29,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.dmt,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(arbitrumTokens.dmt, arbitrumTokens.usdc, FeeAmount.MEDIUM),
  },
  {
    pid: 30,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.grai,
    token1: arbitrumTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(arbitrumTokens.grai, arbitrumTokens.usdc, FeeAmount.LOW),
  },
  {
    pid: 31,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.V3,
    token0: arbitrumTokens.weth,
    token1: arbitrumTokens.swETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(arbitrumTokens.weth, arbitrumTokens.swETH, FeeAmount.LOWEST),
  },
  {
    pid: 2,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.STABLE,
    token0: arbitrumTokens.dlp,
    token1: arbitrumTokens.mdlp,
    lpAddress: '0x0db5e247ab73FBaE16d9301f2977f974EC0AA336',
    stableSwapAddress: '0xd0f0be815a76eFE677c92b07b39a5e972BAf22bD',
    bCakeWrapperAddress: '0xC6B6926ef8B7218F054d64B52Ac455aEd22D690B',
  },
  {
    pid: 178,
    chainId: ChainId.ARBITRUM_ONE,
    protocol: Protocol.STABLE,
    token0: arbitrumTokens.pendle,
    token1: arbitrumTokens.mpendle,
    lpAddress: '0x1A2329546f11e4fE55b853D98Bba2c4678E3105A',
    stableSwapAddress: '0x73ed25e04Aa673ddf7411441098fC5ae19976CE0',
    bCakeWrapperAddress: '0x7Fa4536b3E78643E027Dc34bB5A055517B4D9096',
  },
]

export default arbFarmConfig

/** @deprecated */
export const legacyV3ArbFarmConfig = defineFarmV3ConfigsFromUniversalFarm(
  arbFarmConfig.filter((farm): farm is UniversalFarmConfigV3 => farm.protocol === Protocol.V3),
)

/** @deprecated */
export const legacyFarmConfig: SerializedFarmConfig[] = []
