import { ChainId } from '@pancakeswap/chains'
import { baseTokens } from '@pancakeswap/tokens'
import { FeeAmount, Pool } from '@pancakeswap/v3-sdk'
import { Protocol, UniversalFarmConfig } from '../types'

const pinnedFarmConfig: UniversalFarmConfig[] = [
  {
    pid: 10,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 9,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.usdbc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.usdbc, FeeAmount.LOWEST),
  },
  {
    pid: 5,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.usdc, FeeAmount.LOW),
  },
  {
    pid: 1,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.usdbc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.usdbc, FeeAmount.LOW),
  },
  {
    pid: 6,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.usdc,
    token1: baseTokens.usdbc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.usdc, baseTokens.usdbc, FeeAmount.LOWEST),
  },
  {
    pid: 12,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.cbETH,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.cbETH, baseTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 2,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.cbETH,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.cbETH, baseTokens.weth, FeeAmount.LOW),
  },
]

export const baseFarmConfig: UniversalFarmConfig[] = [
  ...pinnedFarmConfig,
  {
    pid: 38,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.wif, baseTokens.weth, FeeAmount.MEDIUM),
    token0: baseTokens.wif,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 37,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.miggles, FeeAmount.MEDIUM),
    token0: baseTokens.weth,
    token1: baseTokens.miggles,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 36,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.degen, FeeAmount.MEDIUM),
    token0: baseTokens.weth,
    token1: baseTokens.degen,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 35,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.brett, FeeAmount.MEDIUM),
    token0: baseTokens.weth,
    token1: baseTokens.brett,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 34,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.usdz, baseTokens.weth, FeeAmount.LOWEST),
    token0: baseTokens.usdz,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 33,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.usdz, baseTokens.usdc, FeeAmount.LOWEST),
    token0: baseTokens.usdz,
    token1: baseTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 32,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.usdPlus, baseTokens.usdbc, FeeAmount.LOWEST),
    token0: baseTokens.usdPlus,
    token1: baseTokens.usdbc,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 31,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.usdc, baseTokens.usdPlus, FeeAmount.LOWEST),
    token0: baseTokens.usdc,
    token1: baseTokens.usdPlus,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 30,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.usdc, baseTokens.aero, FeeAmount.LOW),
    token0: baseTokens.usdc,
    token1: baseTokens.aero,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 29,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.usdc, baseTokens.usdt, FeeAmount.LOWEST),
    token0: baseTokens.usdc,
    token1: baseTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 28,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.miggles, FeeAmount.LOW),
    token0: baseTokens.weth,
    token1: baseTokens.miggles,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 27,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weeth, baseTokens.weth, FeeAmount.LOWEST),
    token0: baseTokens.weeth,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 26,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.aero, FeeAmount.LOW),
    token0: baseTokens.weth,
    token1: baseTokens.aero,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 25,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.degen, FeeAmount.LOW),
    token0: baseTokens.weth,
    token1: baseTokens.degen,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 24,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.usdt, FeeAmount.LOWEST),
    token0: baseTokens.weth,
    token1: baseTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 23,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.brett, FeeAmount.LOW),
    token0: baseTokens.weth,
    token1: baseTokens.brett,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 22,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.zro,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.zro, FeeAmount.MEDIUM),
  },
  {
    pid: 15,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.usdPlus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.usdPlus, FeeAmount.LOWEST),
  },
  {
    pid: 16,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.usdPlus,
    token1: baseTokens.wstETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.usdPlus, baseTokens.wstETH, FeeAmount.LOWEST),
  },
  {
    pid: 17,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.cbETH,
    token1: baseTokens.usdPlus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.cbETH, baseTokens.usdPlus, FeeAmount.LOWEST),
  },
  {
    pid: 18,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.brett,
    token1: baseTokens.usdPlus,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.brett, baseTokens.usdPlus, FeeAmount.LOW),
  },
  {
    pid: 19,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.degen,
    token1: baseTokens.usdPlus,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.degen, baseTokens.usdPlus, FeeAmount.LOW),
  },
  {
    pid: 20,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.aero,
    token1: baseTokens.usdPlus,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.aero, baseTokens.usdPlus, FeeAmount.LOW),
  },
  {
    pid: 21,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.ovn,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.ovn, FeeAmount.HIGH),
  },
  {
    pid: 14,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.wstETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.wstETH, FeeAmount.LOWEST),
  },
  {
    pid: 13,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.cake,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(baseTokens.cake, baseTokens.weth, FeeAmount.HIGH),
  },

  {
    pid: 11,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.usdbc,
    token1: baseTokens.axlusdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.usdbc, baseTokens.axlusdc, FeeAmount.LOWEST),
  },

  {
    pid: 8,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.tbtc,
    token1: baseTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.tbtc, baseTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 7,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.dai,
    token1: baseTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.dai, baseTokens.usdc, FeeAmount.LOWEST),
  },

  {
    pid: 4,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.weth,
    token1: baseTokens.dai,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(baseTokens.weth, baseTokens.dai, FeeAmount.LOW),
  },
  {
    pid: 3,
    chainId: ChainId.BASE,
    protocol: Protocol.V3,
    token0: baseTokens.dai,
    token1: baseTokens.usdbc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(baseTokens.dai, baseTokens.usdbc, FeeAmount.LOWEST),
  },
]

export default baseFarmConfig
