import { ChainId } from '@pancakeswap/chains'
import { Pair } from '@pancakeswap/sdk'
import { bscTokens } from '@pancakeswap/tokens'
import { FeeAmount, Pool } from '@pancakeswap/v3-sdk'
import { Protocol, UniversalFarmConfig } from '../types'

const pinnedFarmConfig: UniversalFarmConfig[] = [
  {
    pid: 137,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.usdt, FeeAmount.LOWEST),
    token0: bscTokens.usdt,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 5,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.wbnb,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.wbnb, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 149,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.usdc, bscTokens.wbnb, FeeAmount.LOWEST),
    token0: bscTokens.usdc,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 148,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.usdc, bscTokens.wbnb, FeeAmount.LOW),
    token0: bscTokens.usdc,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 7,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.btcb,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.btcb, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 54,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.wbnb,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.wbnb, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 97,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.usdt, FeeAmount.LOW),
    token0: bscTokens.eth,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 1,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.wbnb,
    lpAddress: Pool.getAddress(bscTokens.cake, bscTokens.wbnb, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 4,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.busd,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.busd, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
]

export const bscFarmConfig: UniversalFarmConfig[] = [
  ...pinnedFarmConfig,
  {
    pid: 183,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.btcb, FeeAmount.LOWEST),
    token0: bscTokens.usdt,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 182,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.usdt, FeeAmount.LOWEST),
    token0: bscTokens.eth,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 181,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.wbnb, FeeAmount.LOWEST),
    token0: bscTokens.eth,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 180,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.btcb, bscTokens.kbtc, FeeAmount.LOW),
    token0: bscTokens.btcb,
    token1: bscTokens.kbtc,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 179,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.wstETH, bscTokens.wbnb, FeeAmount.LOW),
    token0: bscTokens.wstETH,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 178,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.wstETH, bscTokens.btcb, FeeAmount.LOW),
    token0: bscTokens.wstETH,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 177,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.wstETH, FeeAmount.LOWEST),
    token0: bscTokens.eth,
    token1: bscTokens.wstETH,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 176,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.btcb, bscTokens.stbtc, FeeAmount.LOWEST),
    token0: bscTokens.btcb,
    token1: bscTokens.stbtc,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 175,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.solvbtcbbn, bscTokens.solvbtc, FeeAmount.LOW),
    token0: bscTokens.solvbtcbbn,
    token1: bscTokens.solvbtc,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 174,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.wsi, FeeAmount.MEDIUM),
    token0: bscTokens.usdt,
    token1: bscTokens.wsi,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 173,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.dexeTkn, bscTokens.boxy, FeeAmount.LOWEST),
    token0: bscTokens.dexeTkn,
    token1: bscTokens.boxy,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 172,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.solvbtc, bscTokens.solvBTCena, FeeAmount.LOW),
    token0: bscTokens.solvbtc,
    token1: bscTokens.solvBTCena,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 171,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.lista, FeeAmount.MEDIUM),
    token0: bscTokens.usdt,
    token1: bscTokens.lista,
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 170,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(bscTokens.zro, bscTokens.wbnb, FeeAmount.HIGH),
    token0: bscTokens.zro,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
  },
  {
    pid: 169,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.lista,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.lista, FeeAmount.HIGH),
  },
  {
    pid: 168,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.axlSTARS,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.axlSTARS, FeeAmount.HIGH),
  },
  {
    pid: 167,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.fury,
    token1: bscTokens.usdt,
    lpAddress: Pool.getAddress(bscTokens.fury, bscTokens.usdt, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 166,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.bnb,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.bnb, bscTokens.busd, FeeAmount.LOWEST),
  },
  {
    pid: 165,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.stone,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.stone, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 164,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.solvbtc,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.solvbtc, bscTokens.btcb, FeeAmount.LOW),
  },
  {
    pid: 163,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.weEth,
    token1: bscTokens.eth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.weEth, bscTokens.eth, FeeAmount.LOWEST),
  },
  {
    pid: 162,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.masa,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.masa, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 161,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.sdt,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.sdt, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 160,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.nmt,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.nmt, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 2,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.cake, bscTokens.busd, FeeAmount.MEDIUM),
  },
  {
    pid: 3,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.cake, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 159,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ego,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.ego, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 158,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.mc,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.mc, FeeAmount.MEDIUM),
  },
  {
    pid: 157,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.mb4,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.mb4, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 156,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.chat,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.chat, FeeAmount.HIGH),
  },
  {
    pid: 155,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.pepe,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.pepe, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 154,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.octavia,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.octavia, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 153,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.pxETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.pxETH, FeeAmount.LOW),
  },
  {
    pid: 152,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.ezETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.ezETH, FeeAmount.LOW),
  },
  {
    pid: 151,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.fil,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.fil, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 150,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.trump,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.trump, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 147,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.fet,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.fet, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 146,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.pxETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.pxETH, FeeAmount.LOWEST),
  },
  {
    pid: 145,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.bnx,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.bnx, FeeAmount.LOW),
  },
  {
    pid: 144,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.osak,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.osak, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 143,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.xrgb,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.xrgb, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 142,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.dmail,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.dmail, FeeAmount.HIGH),
  },
  {
    pid: 141,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.sol,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.sol, FeeAmount.MEDIUM),
  },
  {
    pid: 140,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.sol,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.sol, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 139,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.gtai,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.gtai, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 138,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.aitech,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.aitech, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 136,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.rbnb,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.rbnb, FeeAmount.LOWEST),
  },
  {
    pid: 135,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.manta,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.manta, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 134,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ovn,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.ovn, bscTokens.usdt, FeeAmount.HIGH),
  },
  {
    pid: 133,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.wrose,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.wrose, FeeAmount.LOW),
  },
  {
    pid: 132,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.anyInu,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.anyInu, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 131,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.huahua,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.huahua, FeeAmount.HIGH),
  },
  {
    pid: 130,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.irl,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.irl, FeeAmount.HIGH),
  },
  {
    pid: 129,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdc,
    token1: bscTokens.fdusd,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.usdc, bscTokens.fdusd, FeeAmount.LOWEST),
  },
  {
    pid: 128,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.bnb,
    token1: bscTokens.fdusd,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.bnb, bscTokens.fdusd, FeeAmount.LOW),
  },
  {
    pid: 127,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.fdusd,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.cake, bscTokens.fdusd, FeeAmount.MEDIUM),
  },
  {
    pid: 126,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.fdusd,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.fdusd, FeeAmount.LOW),
  },
  {
    pid: 125,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.btcb,
    token1: bscTokens.fdusd,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.btcb, bscTokens.fdusd, FeeAmount.LOW),
  },
  {
    pid: 124,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.insp,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.insp, bscTokens.bnb, FeeAmount.HIGH),
  },
  {
    pid: 123,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.wrose,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.wrose, FeeAmount.MEDIUM),
  },
  {
    pid: 122,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.cgpt,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.cgpt, FeeAmount.LOW),
  },
  {
    pid: 121,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ckp,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.ckp, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 120,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.pnp,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.pnp, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 119,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.sdcake,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.cake, bscTokens.sdcake, FeeAmount.MEDIUM),
  },
  {
    pid: 118,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.mubi,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.mubi, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 117,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.ordi,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.ordi, FeeAmount.MEDIUM),
  },
  {
    pid: 116,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.nfp,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.nfp, FeeAmount.MEDIUM),
  },
  {
    pid: 115,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.mubi,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.mubi, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 114,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.ordi,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.ordi, FeeAmount.HIGH),
  },
  {
    pid: 113,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.sats,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.sats, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 112,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.rdp,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.rdp, bscTokens.bnb, FeeAmount.MEDIUM),
  },
  {
    pid: 111,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.vai,
    token1: bscTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.vai, bscTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 110,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.vai,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.vai, bscTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 109,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.stg,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.stg, FeeAmount.MEDIUM),
  },
  {
    pid: 108,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.stg,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.stg, bscTokens.busd, FeeAmount.MEDIUM),
  },
  {
    pid: 107,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdv,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.usdv, bscTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 106,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdv,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.usdv, bscTokens.bnb, FeeAmount.LOW),
  },
  {
    pid: 105,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.esRDNT,
    token1: bscTokens.rdnt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.esRDNT, bscTokens.rdnt, FeeAmount.MEDIUM),
  },
  {
    pid: 104,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.ace,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.ace, FeeAmount.MEDIUM),
  },
  {
    pid: 103,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.aioz,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.aioz, bscTokens.bnb, FeeAmount.MEDIUM),
  },
  {
    pid: 102,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.bonk,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.bonk, bscTokens.bnb, FeeAmount.HIGH),
  },
  {
    pid: 101,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.bonk,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.bonk, FeeAmount.HIGH),
  },
  {
    pid: 100,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.kuji,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.kuji, bscTokens.bnb, FeeAmount.HIGH),
  },
  {
    pid: 99,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.btcb, FeeAmount.LOW),
  },
  {
    pid: 98,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.fdusd,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.fdusd, FeeAmount.LOWEST),
  },
  {
    pid: 96,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.twt,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.twt, bscTokens.bnb, FeeAmount.MEDIUM),
  },
  {
    pid: 95,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.chess,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.chess, bscTokens.usdt, FeeAmount.HIGH),
  },
  {
    pid: 94,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.alpaca,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.alpaca, FeeAmount.HIGH),
  },
  {
    pid: 93,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.btt,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.btt, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 92,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.bnb,
    token1: bscTokens.xvs,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.bnb, bscTokens.xvs, FeeAmount.MEDIUM),
  },
  {
    pid: 91,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.trxv2,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.trxv2, FeeAmount.MEDIUM),
  },
  {
    pid: 90,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.axs,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.axs, bscTokens.bnb, FeeAmount.MEDIUM),
  },
  {
    pid: 89,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.wom,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.wom, FeeAmount.HIGH),
  },
  {
    pid: 87,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.rdnt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.rdnt, FeeAmount.MEDIUM),
  },
  {
    pid: 88,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.mbox,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.mbox, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 86,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ltc,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.ltc, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 85,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.sfp,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.sfp, FeeAmount.MEDIUM),
  },
  {
    pid: 45,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.play,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.play, FeeAmount.HIGH),
  },
  {
    pid: 84,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.xcad,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.xcad, FeeAmount.MEDIUM),
  },
  {
    pid: 83,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.mbx,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.mbx, FeeAmount.HIGH),
  },
  {
    pid: 82,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.mbx,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.mbx, FeeAmount.HIGH),
  },
  {
    pid: 81,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wncg,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.wncg, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 80,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.hay,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.hay, bscTokens.usdt, FeeAmount.LOW),
  },
  {
    pid: 79,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.chr,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.chr, FeeAmount.HIGH),
  },
  {
    pid: 78,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.hft,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.hft, bscTokens.usdt, FeeAmount.HIGH),
  },
  {
    pid: 77,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.arv,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.arv, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 76,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.high,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.high, FeeAmount.HIGH),
  },
  {
    pid: 75,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.raca,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.raca, bscTokens.usdt, FeeAmount.HIGH),
  },
  {
    pid: 74,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.sfund,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.sfund, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 73,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.lvl,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.lvl, FeeAmount.HIGH),
  },
  {
    pid: 72,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.gmt,
    token1: bscTokens.usdc,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.gmt, bscTokens.usdc, FeeAmount.MEDIUM),
  },
  {
    pid: 71,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cyber,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.cyber, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 70,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.unshETH,
    token1: bscTokens.eth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.unshETH, bscTokens.eth, FeeAmount.LOW),
  },
  {
    pid: 69,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.dar,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.dar, bscTokens.wbnb, FeeAmount.HIGH),
  },
  {
    pid: 68,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.wmx,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.wmx, FeeAmount.HIGH),
  },
  {
    pid: 67,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.ole,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.ole, FeeAmount.HIGH),
  },
  {
    pid: 66,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.doge,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.doge, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 65,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.dck,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.dck, bscTokens.busd, FeeAmount.MEDIUM),
  },
  {
    pid: 64,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.planet,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.planet, FeeAmount.HIGH),
  },
  {
    pid: 63,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.snbnb,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.snbnb, bscTokens.wbnb, FeeAmount.LOW),
  },
  {
    pid: 62,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.hay,
    token1: bscTokens.eth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.hay, bscTokens.eth, FeeAmount.MEDIUM),
  },
  {
    pid: 61,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.hay,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.hay, bscTokens.btcb, FeeAmount.MEDIUM),
  },
  {
    pid: 60,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.hay,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.hay, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 59,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.tusd,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.tusd, bscTokens.busd, FeeAmount.LOWEST),
  },
  {
    pid: 58,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.uni,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.uni, FeeAmount.MEDIUM),
  },
  {
    pid: 57,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 56,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.btcb, FeeAmount.MEDIUM),
  },
  {
    pid: 55,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.btcb,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.btcb, bscTokens.wbnb, FeeAmount.LOW),
  },
  {
    pid: 53,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eqb,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.eqb, bscTokens.bnb, FeeAmount.HIGH),
  },
  {
    pid: 52,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.axlusdc,
    token1: bscTokens.usdt,
    lpAddress: Pool.getAddress(bscTokens.axlusdc, bscTokens.usdt, FeeAmount.LOWEST),
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 51,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.pendle,
    token1: bscTokens.wbnb,
    lpAddress: Pool.getAddress(bscTokens.pendle, bscTokens.wbnb, FeeAmount.HIGH),
    feeAmount: FeeAmount.HIGH,
  },
  {
    pid: 50,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.xalgo,
    token1: bscTokens.wbnb,
    lpAddress: Pool.getAddress(bscTokens.xalgo, bscTokens.wbnb, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 49,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cgpt,
    token1: bscTokens.busd,
    lpAddress: Pool.getAddress(bscTokens.cgpt, bscTokens.busd, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 48,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.tusd,
    token1: bscTokens.usdt,
    lpAddress: Pool.getAddress(bscTokens.tusd, bscTokens.usdt, FeeAmount.LOWEST),
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 43,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.csix,
    token1: bscTokens.cake,
    lpAddress: Pool.getAddress(bscTokens.csix, bscTokens.cake, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 23,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.axl,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.axl, FeeAmount.MEDIUM),
  },
  {
    pid: 46,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.aog,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.aog, bscTokens.busd, FeeAmount.HIGH),
  },
  {
    pid: 47,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cgpt,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.cgpt, bscTokens.busd, FeeAmount.HIGH),
  },
  {
    pid: 44,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eura,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.eura, bscTokens.usdt, FeeAmount.LOW),
  },
  {
    pid: 42,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.pepe,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.pepe, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 41,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.c98,
    token1: bscTokens.bnb,
    lpAddress: Pool.getAddress(bscTokens.c98, bscTokens.bnb, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 40,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ush,
    token1: bscTokens.bnb,
    lpAddress: Pool.getAddress(bscTokens.ush, bscTokens.bnb, FeeAmount.HIGH),
    feeAmount: FeeAmount.HIGH,
  },
  {
    pid: 39,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.id,
    token1: bscTokens.usdt,
    lpAddress: Pool.getAddress(bscTokens.id, bscTokens.usdt, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 38,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.bnb,
    token1: bscTokens.gal,
    lpAddress: Pool.getAddress(bscTokens.gal, bscTokens.bnb, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 37,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.bnbx,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.bnbx, bscTokens.bnb, FeeAmount.LOW),
  },
  {
    pid: 36,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.peel,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.peel, bscTokens.busd, FeeAmount.MEDIUM),
  },
  {
    pid: 35,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.revv,
    token1: bscTokens.edu,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.revv, bscTokens.edu, FeeAmount.MEDIUM),
  },
  {
    pid: 34,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.edu,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.edu, FeeAmount.MEDIUM),
  },
  {
    pid: 33,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.edu,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.edu, FeeAmount.MEDIUM),
  },
  {
    pid: 32,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.wbeth,
    lpAddress: Pool.getAddress(bscTokens.wbeth, bscTokens.eth, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 31,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.zbc,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.cake, bscTokens.zbc, FeeAmount.HIGH),
  },
  {
    pid: 30,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.champ,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.champ, FeeAmount.HIGH),
  },
  {
    pid: 29,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.unshETH,
    token1: bscTokens.ush,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.unshETH, bscTokens.ush, FeeAmount.MEDIUM),
  },
  {
    pid: 28,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.unshETH,
    token1: bscTokens.usdt,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.unshETH, bscTokens.usdt, FeeAmount.MEDIUM),
  },
  {
    pid: 27,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.cake,
    token1: bscTokens.pstake,
    lpAddress: Pool.getAddress(bscTokens.pstake, bscTokens.cake, FeeAmount.MEDIUM),
    feeAmount: FeeAmount.MEDIUM,
  },
  {
    pid: 26,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.stkbnb,
    lpAddress: Pool.getAddress(bscTokens.stkbnb, bscTokens.wbnb, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 25,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.unw,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.unw, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 24,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.mgp,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.mgp, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 22,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.gq,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.gq, FeeAmount.MEDIUM),
  },
  {
    pid: 20,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.ankrETH,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.ankrETH, FeeAmount.LOW),
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 21,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ankrbnb,
    token1: bscTokens.bnb,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.ankrbnb, bscTokens.bnb, FeeAmount.LOW),
  },
  {
    pid: 6,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.btcb,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.btcb, bscTokens.busd, FeeAmount.LOW),
  },
  {
    pid: 8,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.btcb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.btcb, FeeAmount.MEDIUM),
  },
  {
    pid: 9,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.btcb,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.btcb, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 10,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 11,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.eth,
    token1: bscTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(bscTokens.eth, bscTokens.usdc, FeeAmount.LOW),
  },
  {
    pid: 12,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 13,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdc,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.usdc, bscTokens.busd, FeeAmount.LOWEST),
  },
  {
    pid: 14,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.usdt,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(bscTokens.usdt, bscTokens.busd, FeeAmount.LOWEST),
  },
  {
    pid: 15,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.wbnb,
    token1: bscTokens.link,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.wbnb, bscTokens.link, FeeAmount.MEDIUM),
  },
  {
    pid: 16,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.xrp,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.xrp, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 17,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.trx,
    token1: bscTokens.busd,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.trx, bscTokens.busd, FeeAmount.MEDIUM),
  },
  {
    pid: 18,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.ada,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.ada, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 19,
    chainId: ChainId.BSC,
    protocol: Protocol.V3,
    token0: bscTokens.dot,
    token1: bscTokens.wbnb,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(bscTokens.dot, bscTokens.wbnb, FeeAmount.MEDIUM),
  },
  {
    pid: 2,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.cake,
    token1: bscTokens.wbnb,
    lpAddress: Pair.getAddress(bscTokens.cake, bscTokens.wbnb),
  },
  {
    pid: 47,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.cake,
    token1: bscTokens.usdt,
    lpAddress: Pair.getAddress(bscTokens.cake, bscTokens.usdt),
  },

  //    * V3 by order of release (some may be out of PID order due to multiplier boost)
  {
    pid: 9,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.wbnb,
    token1: bscTokens.xvs,
    lpAddress: Pair.getAddress(bscTokens.wbnb, bscTokens.xvs),
  },
  {
    pid: 182,
    chainId: ChainId.BSC,
    protocol: Protocol.STABLE,
    lpAddress: '0x4cBEa76B4A1c42C356B4c52B0314A98313fFE9df',
    stableSwapAddress: '0xfF5Ce4846A3708EA9befa6c3Ab145e63f65DC045',
    token0: bscTokens.mwbeth,
    token1: bscTokens.wbeth,
  },
  {
    pid: 180,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.wbnb,
    token1: bscTokens.mgp,
    lpAddress: Pair.getAddress(bscTokens.wbnb, bscTokens.mgp),
  },
  {
    pid: 181,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.pnp,
    token1: bscTokens.wbnb,
    lpAddress: Pair.getAddress(bscTokens.pnp, bscTokens.wbnb),
  },
  {
    pid: 179,
    chainId: ChainId.BSC,
    protocol: Protocol.STABLE,
    token0: bscTokens.mdlp,
    token1: bscTokens.dlp,
    lpAddress: '0xA2915ae3bc8C6C03f59496B6Dd26aa6a4335b788',
    stableSwapAddress: '0x25d0eD3b1cE5aF0F3Ac7da4b39B46FC409bF67e2',
  },
  {
    pid: 178,
    chainId: ChainId.BSC,
    protocol: Protocol.STABLE,
    token0: bscTokens.mpendle,
    token1: bscTokens.pendle,
    lpAddress: '0x183F325b33d190597D80d1B46D865d0250fD9BF2',
    stableSwapAddress: '0xD8CB82059da7215b1a9604E845d49D3e78d0f95A',
  },
  {
    pid: 177,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.ckp,
    token1: bscTokens.mcake,
    lpAddress: Pair.getAddress(bscTokens.ckp, bscTokens.mcake),
  },
  {
    pid: 176,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.rdp,
    token1: bscTokens.wbnb,
    lpAddress: Pair.getAddress(bscTokens.rdp, bscTokens.wbnb),
  },
  {
    pid: 175,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.wbnb,
    token1: bscTokens.hzn,
    lpAddress: Pair.getAddress(bscTokens.wbnb, bscTokens.hzn),
  },
  {
    pid: 173,
    chainId: ChainId.BSC,
    protocol: Protocol.STABLE,
    token0: bscTokens.cake,
    token1: bscTokens.sdcake,
    lpAddress: '0xB1D54d76E2cB9425Ec9c018538cc531440b55dbB',
    stableSwapAddress: '0xb8204D31379A9B317CD61C833406C972F58ecCbC',
  },
  {
    pid: 174,
    chainId: ChainId.BSC,
    protocol: Protocol.STABLE,
    token0: bscTokens.cake,
    token1: bscTokens.mcake,
    lpAddress: '0xb9dC6396AcFFD24E0f69Dfd3231fDaeB31514D02',
    stableSwapAddress: '0xc54d35a8Cfd9f6dAe50945Df27A91C9911A03ab1',
  },
  {
    pid: 163,
    chainId: ChainId.BSC,
    protocol: Protocol.STABLE,
    token0: bscTokens.hay,
    token1: bscTokens.usdt,
    lpAddress: '0xB2Aa63f363196caba3154D4187949283F085a488',
    stableSwapAddress: '0xb1Da7D2C257c5700612BdE35C8d7187dc80d79f1',
  },
  {
    pid: 42,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.mbox,
    token1: bscTokens.wbnb,
    lpAddress: Pair.getAddress(bscTokens.mbox, bscTokens.wbnb),
  },
  {
    pid: 8,
    chainId: ChainId.BSC,
    protocol: Protocol.V2,
    token0: bscTokens.twt,
    token1: bscTokens.wbnb,
    lpAddress: Pair.getAddress(bscTokens.twt, bscTokens.wbnb),
  },
]

export default bscFarmConfig
