import { ChainId } from '@pancakeswap/chains'
import { polygonZkEvmTokens } from '@pancakeswap/tokens'
import { FeeAmount, Pool } from '@pancakeswap/v3-sdk'
import { defineFarmV3ConfigsFromUniversalFarm } from '../defineFarmV3Configs'
import { Protocol, SerializedFarmConfig, UniversalFarmConfig, UniversalFarmConfigV3 } from '../types'

const pinnedFarmConfig: UniversalFarmConfig[] = [
  {
    pid: 15,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 1,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.usdc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.usdc, FeeAmount.LOW),
  },
  {
    pid: 2,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdt,
    token1: polygonZkEvmTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdt, polygonZkEvmTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 3,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdt,
    token1: polygonZkEvmTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdt, polygonZkEvmTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 16,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.wbtc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.wbtc, FeeAmount.LOWEST),
  },
  {
    pid: 17,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.matic,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.matic, FeeAmount.LOW),
  },
  {
    pid: 4,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.matic,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.matic, FeeAmount.MEDIUM),
  },
]

export const polygonZkEVMFarmConfig: UniversalFarmConfig[] = [
  ...pinnedFarmConfig,
  {
    pid: 26,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.pol, polygonZkEvmTokens.matic, FeeAmount.LOWEST),
    token0: polygonZkEvmTokens.pol,
    token1: polygonZkEvmTokens.matic,
    feeAmount: FeeAmount.LOWEST,
  },
  {
    pid: 25,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.pol, polygonZkEvmTokens.weth, FeeAmount.LOW),
    token0: polygonZkEvmTokens.pol,
    token1: polygonZkEvmTokens.weth,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 24,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdt, polygonZkEvmTokens.pol, FeeAmount.LOW),
    token0: polygonZkEvmTokens.usdt,
    token1: polygonZkEvmTokens.pol,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 23,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.pol, polygonZkEvmTokens.usdce, FeeAmount.LOW),
    token0: polygonZkEvmTokens.pol,
    token1: polygonZkEvmTokens.usdce,
    feeAmount: FeeAmount.LOW,
  },
  {
    pid: 22,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdc,
    token1: polygonZkEvmTokens.dai,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdc, polygonZkEvmTokens.dai, FeeAmount.LOWEST),
  },
  {
    pid: 21,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdt,
    token1: polygonZkEvmTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdt, polygonZkEvmTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 20,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdce,
    token1: polygonZkEvmTokens.grai,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdce, polygonZkEvmTokens.grai, FeeAmount.LOW),
  },
  {
    pid: 19,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.cake,
    token1: polygonZkEvmTokens.weth,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.cake, polygonZkEvmTokens.weth, FeeAmount.HIGH),
  },
  {
    pid: 18,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.cake,
    token1: polygonZkEvmTokens.usdc,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.cake, polygonZkEvmTokens.usdc, FeeAmount.HIGH),
  },

  {
    pid: 14,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.rsETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.rsETH, FeeAmount.LOW),
  },
  {
    pid: 13,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.reth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.reth, FeeAmount.LOW),
  },
  {
    pid: 12,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.wstETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.wstETH, FeeAmount.LOW),
  },
  {
    pid: 11,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.wstETH,
    token1: polygonZkEvmTokens.reth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.wstETH, polygonZkEvmTokens.reth, FeeAmount.LOW),
  },
  {
    pid: 8,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.wstETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.wstETH, FeeAmount.LOWEST),
  },
  {
    pid: 9,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.reth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.reth, FeeAmount.LOWEST),
  },
  {
    pid: 10,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.rsETH,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.rsETH, FeeAmount.LOWEST),
  },
  {
    pid: 7,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdce,
    token1: polygonZkEvmTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdce, polygonZkEvmTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 5,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.usdc,
    token1: polygonZkEvmTokens.grai,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.usdc, polygonZkEvmTokens.grai, FeeAmount.LOW),
  },
  {
    pid: 6,
    chainId: ChainId.POLYGON_ZKEVM,
    protocol: Protocol.V3,
    token0: polygonZkEvmTokens.weth,
    token1: polygonZkEvmTokens.wbtc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(polygonZkEvmTokens.weth, polygonZkEvmTokens.wbtc, FeeAmount.LOW),
  },
]

export default polygonZkEVMFarmConfig

/** @deprecated */
export const legacyV3PolygonZkEVMFarmConfig = defineFarmV3ConfigsFromUniversalFarm(
  polygonZkEVMFarmConfig.filter((farm): farm is UniversalFarmConfigV3 => farm.protocol === Protocol.V3),
)

/** @deprecated */
export const legacyFarmConfig: SerializedFarmConfig[] = []
