import { ChainId } from '@pancakeswap/chains'
import { zksyncTokens } from '@pancakeswap/tokens'
import { FeeAmount, Pool } from '@pancakeswap/v3-sdk'
import { defineFarmV3ConfigsFromUniversalFarm } from '../defineFarmV3Configs'
import { Protocol, SerializedFarmConfig, UniversalFarmConfig, UniversalFarmConfigV3 } from '../types'

const pinnedFarmConfig: UniversalFarmConfig[] = [
  {
    pid: 29,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.zk,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(zksyncTokens.zk, zksyncTokens.weth, FeeAmount.MEDIUM),
  },

  {
    pid: 33,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdcNative,
    token1: zksyncTokens.zk,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(zksyncTokens.usdcNative, zksyncTokens.zk, FeeAmount.MEDIUM),
  },
  {
    pid: 31,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.zk,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.zk, FeeAmount.MEDIUM),
  },
  {
    pid: 5,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.cake,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(zksyncTokens.cake, zksyncTokens.weth, FeeAmount.MEDIUM),
  },

  {
    pid: 8,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 1,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 18,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdt,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdt, zksyncTokens.weth, FeeAmount.LOWEST),
  },
  {
    pid: 12,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdt,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.usdt, zksyncTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 3,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 6,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.weth,
    token1: zksyncTokens.wbtc,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.weth, zksyncTokens.wbtc, FeeAmount.LOW),
  },
]

export const zkSyncFarmConfig: UniversalFarmConfig[] = [
  ...pinnedFarmConfig,
  {
    pid: 34,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.weth,
    token1: zksyncTokens.rf,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(zksyncTokens.weth, zksyncTokens.rf, FeeAmount.HIGH),
  },

  {
    pid: 32,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdcNative,
    token1: zksyncTokens.zk,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(zksyncTokens.usdcNative, zksyncTokens.zk, FeeAmount.HIGH),
  },

  {
    pid: 30,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.zk,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.zk, FeeAmount.HIGH),
  },
  {
    pid: 28,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.zk,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(zksyncTokens.zk, zksyncTokens.weth, FeeAmount.HIGH),
  },
  {
    pid: 27,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdcNative,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.usdcNative, zksyncTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 26,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdcNative,
    token1: zksyncTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdcNative, zksyncTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 25,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdcNative,
    token1: zksyncTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdcNative, zksyncTokens.usdc, FeeAmount.LOWEST),
  },
  {
    pid: 24,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdt,
    token1: zksyncTokens.usdtPlus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdt, zksyncTokens.usdtPlus, FeeAmount.LOWEST),
  },
  {
    pid: 23,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdPlus,
    token1: zksyncTokens.usdtPlus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdPlus, zksyncTokens.usdtPlus, FeeAmount.LOWEST),
  },
  {
    pid: 22,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.grai,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.grai, FeeAmount.LOWEST),
  },
  {
    pid: 21,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.grai,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.grai, FeeAmount.LOW),
  },
  {
    pid: 20,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.weth,
    token1: zksyncTokens.wethe,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.weth, zksyncTokens.wethe, FeeAmount.LOW),
  },
  {
    pid: 19,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.weth,
    token1: zksyncTokens.wbtc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.weth, zksyncTokens.wbtc, FeeAmount.LOWEST),
  },
  {
    pid: 17,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.dai,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.dai, FeeAmount.LOWEST),
  },
  {
    pid: 16,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdt,
    token1: zksyncTokens.dai,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdt, zksyncTokens.dai, FeeAmount.LOWEST),
  },
  {
    pid: 15,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.reth,
    token1: zksyncTokens.wstETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.reth, zksyncTokens.wstETH, FeeAmount.LOW),
  },
  {
    pid: 14,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.wstETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.wstETH, FeeAmount.LOW),
  },
  {
    pid: 13,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.weth,
    token1: zksyncTokens.wstETH,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.weth, zksyncTokens.wstETH, FeeAmount.LOW),
  },

  {
    pid: 11,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.usdPlus,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.usdPlus, FeeAmount.LOWEST),
  },
  {
    pid: 10,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.reth,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.LOW,
    lpAddress: Pool.getAddress(zksyncTokens.reth, zksyncTokens.weth, FeeAmount.LOW),
  },
  {
    pid: 9,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.busd,
    token1: zksyncTokens.usdt,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.busd, zksyncTokens.usdt, FeeAmount.LOWEST),
  },
  {
    pid: 2,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.usdc,
    token1: zksyncTokens.weth,
    feeAmount: FeeAmount.MEDIUM,
    lpAddress: Pool.getAddress(zksyncTokens.usdc, zksyncTokens.weth, FeeAmount.MEDIUM),
  },

  {
    pid: 4,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.weth,
    token1: zksyncTokens.tes,
    feeAmount: FeeAmount.HIGH,
    lpAddress: Pool.getAddress(zksyncTokens.weth, zksyncTokens.tes, FeeAmount.HIGH),
  },

  {
    pid: 7,
    chainId: ChainId.ZKSYNC,
    protocol: Protocol.V3,
    token0: zksyncTokens.busd,
    token1: zksyncTokens.usdc,
    feeAmount: FeeAmount.LOWEST,
    lpAddress: Pool.getAddress(zksyncTokens.busd, zksyncTokens.usdc, FeeAmount.LOWEST),
  },
]
export default zkSyncFarmConfig

/** @deprecated */
export const legacyV3ZkSyncFarmConfig = defineFarmV3ConfigsFromUniversalFarm(
  zkSyncFarmConfig.filter((farm): farm is UniversalFarmConfigV3 => farm.protocol === Protocol.V3),
)

/** @deprecated */
export const legacyFarmConfig: SerializedFarmConfig[] = []
