type ProviderInfo = {
  countryCode: string
  countryName: string
  continent: string
  buyAvailable: boolean
  sellAvailable: boolean
  states?: any[]
}

type ProviderData = {
  [provider: string]: ProviderInfo[]
}

export const providerData: ProviderData = {
  Provider1: [
    {
      countryCode: 'DZ',
      countryName: 'Algeria',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AD',
      countryName: 'Andorra',
      continent: 'Europe',
      buyAvailable: true,
      sellAvailable: true,
    },
    {
      countryCode: 'AO',
      countryName: 'Angola',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AG',
      countryName: 'Antigua and Barbuda',
      continent: 'North America',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AR',
      countryName: 'Argentina',
      continent: 'South America',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AM',
      countryName: 'Armenia',
      continent: 'Asia',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AU',
      countryName: 'Australia',
      continent: 'Oceania',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AT',
      countryName: 'Austria',
      continent: 'Europe',
      buyAvailable: true,
      sellAvailable: true,
    },
    {
      countryCode: 'AZ',
      countryName: 'Azerbaijan',
      continent: 'Asia',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BH',
      countryName: 'Bahrain',
      continent: 'Asia',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BE',
      countryName: 'Belgium',
      continent: 'Europe',
      buyAvailable: true,
      sellAvailable: true,
    },
    {
      countryCode: 'BZ',
      countryName: 'Belize',
      continent: 'North America',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BJ',
      countryName: 'Benin',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BT',
      countryName: 'Bhutan',
      continent: 'Asia',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BA',
      countryName: 'Bosnia and Herzegovina',
      continent: 'Europe',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BR',
      countryName: 'Brazil',
      continent: 'South America',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BN',
      countryName: 'Brunei Darussalam',
      continent: 'Asia',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'BG',
      countryName: 'Bulgaria',
      continent: 'Europe',
      buyAvailable: true,
      sellAvailable: true,
    },
    {
      countryCode: 'BI',
      countryName: 'Burundi',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'CV',
      countryName: 'Cabo Verde',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'CM',
      countryName: 'Cameroon',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },

    {
      countryCode: 'DZ',
      countryName: 'Algeria',
      continent: 'Africa',
      buyAvailable: true,
      sellAvailable: false,
    },
    {
      countryCode: 'AD',
      countryName: 'Andorra',
      continent: 'Europe',
      buyAvailable: true,
      sellAvailable: true,
    },
    {
      countryCode: 'CA',
      countryName: 'Canada',
      continent: 'North America',
      buyAvailable: true,
      sellAvailable: false,
      states: [
        {
          code: 'AB',
          name: 'Alberta',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'BC',
          name: 'British Columbia',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'MB',
          name: 'Manitoba',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'NB',
          name: 'New Brunswick',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'NL',
          name: 'Newfoundland and Labrador',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'NS',
          name: 'Nova Scotia',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'NT',
          name: 'Northwest Territories',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'NU',
          name: 'Nunavut',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'ON',
          name: 'Ontario',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'PE',
          name: 'Prince Edward Island',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'QC',
          name: 'Quebec',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'SK',
          name: 'Saskatchewan',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },
        {
          code: 'YT',
          name: 'Yukon',
          isBuyAllowed: true,
          isNftAllowed: true,
          isSellAllowed: false,
          isAllowed: true,
        },

        {
          countryCode: 'DZ',
          countryName: 'Algeria',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'AD',
          countryName: 'Andorra',
          continent: 'Europe',
          buyAvailable: true,
          sellAvailable: true,
        },
        // Add more objects here...
        {
          countryCode: 'CF',
          countryName: 'Central African Republic',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'TD',
          countryName: 'Chad',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'CL',
          countryName: 'Chile',
          continent: 'South America',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'CO',
          countryName: 'Colombia',
          continent: 'South America',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'CG',
          countryName: 'Congo',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'CR',
          countryName: 'Costa Rica',
          continent: 'North America',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'HR',
          countryName: 'Croatia',
          continent: 'Europe',
          buyAvailable: true,
          sellAvailable: true,
        },
        {
          countryCode: 'CY',
          countryName: 'Cyprus',
          continent: 'Europe',
          buyAvailable: true,
          sellAvailable: true,
        },
        {
          countryCode: 'CZ',
          countryName: 'Czechia',
          continent: 'Europe',
          buyAvailable: true,
          sellAvailable: true,
        },
        {
          countryCode: 'DK',
          countryName: 'Denmark',
          continent: 'Europe',
          buyAvailable: true,
          sellAvailable: true,
        },
        {
          countryCode: 'DJ',
          countryName: 'Djibouti',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'DM',
          countryName: 'Dominica',
          continent: 'North America',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'DO',
          countryName: 'Dominican Republic',
          continent: 'North America',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'EG',
          countryName: 'Egypt',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'SV',
          countryName: 'El Salvador',
          continent: 'North America',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'GQ',
          countryName: 'Equatorial Guinea',
          continent: 'Africa',
          buyAvailable: true,
          sellAvailable: false,
        },
        {
          countryCode: 'EE',
          countryName: 'Estonia',
          continent: 'Europe',
          buyAvailable: true,
          sellAvailable: true,
        },
      ],
    },
  ],
}

export const exradata = {
  0: {
    alpha2: 'DZ',
    alpha3: 'DZA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Algeria',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  1: {
    alpha2: 'AD',
    alpha3: 'AND',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Andorra',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  2: {
    alpha2: 'AO',
    alpha3: 'AGO',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Angola',
    continent: 'Africa',
    suggestedDocuments: ['national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  3: {
    alpha2: 'AG',
    alpha3: 'ATG',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Antigua and Barbuda',
    continent: 'North America',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  4: {
    alpha2: 'AR',
    alpha3: 'ARG',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Argentina',
    continent: 'South America',
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  5: {
    alpha2: 'AM',
    alpha3: 'ARM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Armenia',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence', 'national_identity_card', 'passport'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  6: {
    alpha2: 'AU',
    alpha3: 'AUS',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Australia',
    continent: 'Oceania',
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  7: {
    alpha2: 'AT',
    alpha3: 'AUT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Austria',
    continent: 'Europe',
    suggestedDocuments: ['passport'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  8: {
    alpha2: 'AZ',
    alpha3: 'AZE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Azerbaijan',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  9: {
    alpha2: 'BH',
    alpha3: 'BHR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Bahrain',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  10: {
    alpha2: 'BE',
    alpha3: 'BEL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Belgium',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  11: {
    alpha2: 'BZ',
    alpha3: 'BLZ',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Belize',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  12: {
    alpha2: 'BJ',
    alpha3: 'BEN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Benin',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  13: {
    alpha2: 'BT',
    alpha3: 'BTN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Bhutan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  14: {
    alpha2: 'BA',
    alpha3: 'BIH',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Bosnia and Herzegovina',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  15: {
    alpha2: 'BR',
    alpha3: 'BRA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Brazil',
    continent: 'South America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  16: {
    alpha2: 'BN',
    alpha3: 'BRN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Brunei Darussalam',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  17: {
    alpha2: 'BG',
    alpha3: 'BGR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Bulgaria',
    continent: 'Europe',
    suggestedDocuments: ['driving_licence', 'residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  18: {
    alpha2: 'BI',
    alpha3: 'BDI',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Burundi',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  19: {
    alpha2: 'CV',
    alpha3: 'CPV',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Cabo Verde',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  20: {
    alpha2: 'CM',
    alpha3: 'CMR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Cameroon',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  21: {
    alpha2: 'CA',
    alpha3: 'CAN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Canada',
    continent: 'North America',
    states: [
      {
        code: 'AB',
        name: 'Alberta',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'BC',
        name: 'British Columbia',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'MB',
        name: 'Manitoba',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'NB',
        name: 'New Brunswick',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'NL',
        name: 'Newfoundland and Labrador',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'NS',
        name: 'Nova Scotia',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'NT',
        name: 'Northwest Territories',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'NU',
        name: 'Nunavut',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'ON',
        name: 'Ontario',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'PE',
        name: 'Prince Edward Island',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'QC',
        name: 'Quebec',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'SK',
        name: 'Saskatchewan',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'YT',
        name: 'Yukon',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        isAllowed: true,
      },
    ],
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  22: {
    alpha2: 'CF',
    alpha3: 'CAF',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Central African Republic',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  23: {
    alpha2: 'TD',
    alpha3: 'TCD',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Chad',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  24: {
    alpha2: 'CL',
    alpha3: 'CHL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Chile',
    continent: 'South America',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  25: {
    alpha2: 'CO',
    alpha3: 'COL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Colombia',
    continent: 'South America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  26: {
    alpha2: 'CG',
    alpha3: 'COG',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Congo',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  27: {
    alpha2: 'CR',
    alpha3: 'CRI',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Costa Rica',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  28: {
    alpha2: 'HR',
    alpha3: 'HRV',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Croatia',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  29: {
    alpha2: 'CY',
    alpha3: 'CYP',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Cyprus',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  30: {
    alpha2: 'CZ',
    alpha3: 'CZE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Czechia',
    continent: 'Europe',
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  31: {
    alpha2: 'DK',
    alpha3: 'DNK',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Denmark',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  32: {
    alpha2: 'DJ',
    alpha3: 'DJI',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Djibouti',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  33: {
    alpha2: 'DM',
    alpha3: 'DMA',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Dominica',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  34: {
    alpha2: 'DO',
    alpha3: 'DOM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Dominican Republic',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  35: {
    alpha2: 'EG',
    alpha3: 'EGY',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Egypt',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  36: {
    alpha2: 'SV',
    alpha3: 'SLV',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'El Salvador',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  37: {
    alpha2: 'GQ',
    alpha3: 'GNQ',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Equatorial Guinea',
    continent: 'Africa',
    supportedDocuments: ['passport', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  38: {
    alpha2: 'EE',
    alpha3: 'EST',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Estonia',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  39: {
    alpha2: 'ET',
    alpha3: 'ETH',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Ethiopia',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  40: {
    alpha2: 'FJ',
    alpha3: 'FJI',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Fiji',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  41: {
    alpha2: 'FI',
    alpha3: 'FIN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Finland',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  42: {
    alpha2: 'FR',
    alpha3: 'FRA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'France',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card', 'passport', 'residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  43: {
    alpha2: 'GA',
    alpha3: 'GAB',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Gabon',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  44: {
    alpha2: 'GM',
    alpha3: 'GMB',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Gambia',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  45: {
    alpha2: 'GE',
    alpha3: 'GEO',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Georgia',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  46: {
    alpha2: 'DE',
    alpha3: 'DEU',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Germany',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card', 'residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  47: {
    alpha2: 'GR',
    alpha3: 'GRC',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Greece',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  48: {
    alpha2: 'GD',
    alpha3: 'GRD',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Grenada',
    continent: 'North America',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  49: {
    alpha2: 'GT',
    alpha3: 'GTM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Guatemala',
    continent: 'North America',
    suggestedDocuments: ['national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  50: {
    alpha2: 'GN',
    alpha3: 'GIN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Guinea',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  51: {
    alpha2: 'GW',
    alpha3: 'GNB',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Guinea-Bissau',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  52: {
    alpha2: 'GY',
    alpha3: 'GUY',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Guyana',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  53: {
    alpha2: 'HN',
    alpha3: 'HND',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Honduras',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  54: {
    alpha2: 'HK',
    alpha3: 'HKG',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Hong Kong',
    continent: 'Asia',
    supportedDocuments: ['passport', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  55: {
    alpha2: 'HU',
    alpha3: 'HUN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Hungary',
    continent: 'Europe',
    suggestedDocuments: ['residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  56: {
    alpha2: 'IN',
    alpha3: 'IND',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'India',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  57: {
    alpha2: 'ID',
    alpha3: 'IDN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Indonesia',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  58: {
    alpha2: 'IE',
    alpha3: 'IRL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Ireland',
    continent: 'Europe',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  59: {
    alpha2: 'IL',
    alpha3: 'ISR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Israel',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  60: {
    alpha2: 'IT',
    alpha3: 'ITA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Italy',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  61: {
    alpha2: 'JO',
    alpha3: 'JOR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Jordan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  62: {
    alpha2: 'KZ',
    alpha3: 'KAZ',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Kazakhstan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  63: {
    alpha2: 'KE',
    alpha3: 'KEN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Kenya',
    continent: 'Africa',
    supportedDocuments: ['passport', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  64: {
    alpha2: 'KR',
    alpha3: 'KOR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Korea, Republic of',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  65: {
    alpha2: 'KW',
    alpha3: 'KWT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Kuwait',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  66: {
    alpha2: 'LA',
    alpha3: 'LAO',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: "Lao People's Democratic Republic",
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  67: {
    alpha2: 'LV',
    alpha3: 'LVA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Latvia',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  68: {
    alpha2: 'LB',
    alpha3: 'LBN',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Lebanon',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  69: {
    alpha2: 'LS',
    alpha3: 'LSO',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Lesotho',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  70: {
    alpha2: 'LY',
    alpha3: 'LBY',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Libya',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  71: {
    alpha2: 'LI',
    alpha3: 'LIE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Liechtenstein',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  72: {
    alpha2: 'LT',
    alpha3: 'LTU',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Lithuania',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  73: {
    alpha2: 'LU',
    alpha3: 'LUX',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Luxembourg',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  74: {
    alpha2: 'MG',
    alpha3: 'MDG',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Madagascar',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  75: {
    alpha2: 'MW',
    alpha3: 'MWI',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Malawi',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  76: {
    alpha2: 'MY',
    alpha3: 'MYS',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Malaysia',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  77: {
    alpha2: 'MV',
    alpha3: 'MDV',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Maldives',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  78: {
    alpha2: 'ML',
    alpha3: 'MLI',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Mali',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  79: {
    alpha2: 'MH',
    alpha3: 'MHL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Marshall Islands',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  80: {
    alpha2: 'MR',
    alpha3: 'MRT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Mauritania',
    continent: 'Africa',
    supportedDocuments: ['passport', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  81: {
    alpha2: 'MX',
    alpha3: 'MEX',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Mexico',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  82: {
    alpha2: 'FM',
    alpha3: 'FSM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Micronesia (Federated States of)',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  83: {
    alpha2: 'MD',
    alpha3: 'MDA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Moldova, Republic of',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  84: {
    alpha2: 'MC',
    alpha3: 'MCO',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Monaco',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  85: {
    alpha2: 'ME',
    alpha3: 'MNE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Montenegro',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  86: {
    alpha2: 'MZ',
    alpha3: 'MOZ',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Mozambique',
    continent: 'Africa',
    supportedDocuments: ['passport', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  87: {
    alpha2: 'NA',
    alpha3: 'NAM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Namibia',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  88: {
    alpha2: 'NR',
    alpha3: 'NRU',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Nauru',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  89: {
    alpha2: 'NP',
    alpha3: 'NPL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Nepal',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  90: {
    alpha2: 'NL',
    alpha3: 'NLD',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Netherlands',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  91: {
    alpha2: 'NZ',
    alpha3: 'NZL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'New Zealand',
    continent: 'Oceania',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  92: {
    alpha2: 'NE',
    alpha3: 'NER',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Niger',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  93: {
    alpha2: 'NG',
    alpha3: 'NGA',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Nigeria',
    continent: 'Africa',
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  94: {
    alpha2: 'MK',
    alpha3: 'MKD',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'North Macedonia',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  95: {
    alpha2: 'NO',
    alpha3: 'NOR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Norway',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  96: {
    alpha2: 'OM',
    alpha3: 'OMN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Oman',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  97: {
    alpha2: 'PW',
    alpha3: 'PLW',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Palau',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  98: {
    alpha2: 'PS',
    alpha3: 'PSE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Palestine, State of',
    continent: 'Asia',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  99: {
    alpha2: 'PG',
    alpha3: 'PNG',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Papua New Guinea',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  100: {
    alpha2: 'PY',
    alpha3: 'PRY',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Paraguay',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  101: {
    alpha2: 'PE',
    alpha3: 'PER',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Peru',
    continent: 'Asia',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  102: {
    alpha2: 'PH',
    alpha3: 'PHL',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Philippines',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  103: {
    alpha2: 'PL',
    alpha3: 'POL',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Poland',
    continent: 'Europe',
    suggestedDocuments: ['residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  104: {
    alpha2: 'PT',
    alpha3: 'PRT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Portugal',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  105: {
    alpha2: 'QA',
    alpha3: 'QAT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Qatar',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  106: {
    alpha2: 'RO',
    alpha3: 'ROU',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Romania',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  107: {
    alpha2: 'RU',
    alpha3: 'RUS',
    isBuyAllowed: false,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Russian Federation',
    continent: 'Europe',
    suggestedDocuments: ['driving_licence', 'passport'],
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: false,
  },
  108: {
    alpha2: 'RW',
    alpha3: 'RWA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Rwanda',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  109: {
    alpha2: 'KN',
    alpha3: 'KNA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Saint Kitts and Nevis',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  110: {
    alpha2: 'LC',
    alpha3: 'LCA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Saint Lucia',
    continent: 'North America',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  111: {
    alpha2: 'WS',
    alpha3: 'WSM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Samoa',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  112: {
    alpha2: 'SM',
    alpha3: 'SMR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'San Marino',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  113: {
    alpha2: 'ST',
    alpha3: 'STP',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Sao Tome and Principe',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  114: {
    alpha2: 'SA',
    alpha3: 'SAU',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Saudi Arabia',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  115: {
    alpha2: 'RS',
    alpha3: 'SRB',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Serbia',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  116: {
    alpha2: 'SC',
    alpha3: 'SYC',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Seychelles',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  117: {
    alpha2: 'SL',
    alpha3: 'SLE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Sierra Leone',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  118: {
    alpha2: 'SG',
    alpha3: 'SGP',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Singapore',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  119: {
    alpha2: 'SK',
    alpha3: 'SVK',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Slovakia',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card', 'residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  120: {
    alpha2: 'SI',
    alpha3: 'SVN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Slovenia',
    continent: 'Europe',
    suggestedDocuments: ['driving_licence', 'national_identity_card', 'residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  121: {
    alpha2: 'SB',
    alpha3: 'SLB',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Solomon Islands',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  122: {
    alpha2: 'SO',
    alpha3: 'SOM',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Somalia',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  123: {
    alpha2: 'ZA',
    alpha3: 'ZAF',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'South Africa',
    continent: 'Africa',
    suggestedDocuments: ['residence_permit'],
    supportedDocuments: ['passport', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  124: {
    alpha2: 'ES',
    alpha3: 'ESP',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Spain',
    continent: 'Europe',
    suggestedDocuments: ['national_identity_card', 'residence_permit'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  125: {
    alpha2: 'LK',
    alpha3: 'LKA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Sri Lanka',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  126: {
    alpha2: 'SR',
    alpha3: 'SUR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Suriname',
    continent: 'South America',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  127: {
    alpha2: 'SE',
    alpha3: 'SWE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Sweden',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  128: {
    alpha2: 'CH',
    alpha3: 'CHE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Switzerland',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  129: {
    alpha2: 'TW',
    alpha3: 'TWN',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Taiwan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  130: {
    alpha2: 'TJ',
    alpha3: 'TJK',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Tajikistan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  131: {
    alpha2: 'TZ',
    alpha3: 'TZA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Tanzania, United Republic of',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  132: {
    alpha2: 'TH',
    alpha3: 'THA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Thailand',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  133: {
    alpha2: 'TG',
    alpha3: 'TGO',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Togo',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  134: {
    alpha2: 'TO',
    alpha3: 'TON',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Tonga',
    continent: 'Oceania',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  135: {
    alpha2: 'TN',
    alpha3: 'TUN',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Tunisia',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  136: {
    alpha2: 'TR',
    alpha3: 'TUR',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Turkey',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  137: {
    alpha2: 'TM',
    alpha3: 'TKM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Turkmenistan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  138: {
    alpha2: 'UA',
    alpha3: 'UKR',
    isBuyAllowed: false,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Ukraine',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: false,
  },
  139: {
    alpha2: 'AE',
    alpha3: 'ARE',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'United Arab Emirates',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  140: {
    alpha2: 'GB',
    alpha3: 'GBR',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'United Kingdom',
    continent: 'Europe',
    suggestedDocuments: ['driving_licence'],
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  141: {
    alpha2: 'OT',
    alpha3: 'BOT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'United Kingdom Overseas Territory',
    continent: 'Europe',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  142: {
    alpha2: 'US',
    alpha3: 'USA',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'United States of America',
    continent: 'North America',
    states: [
      {
        code: 'AL',
        name: 'Alabama',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'AK',
        name: 'Alaska',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'AZ',
        name: 'Arizona',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'AR',
        name: 'Arkansas',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'CA',
        name: 'California',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'CO',
        name: 'Colorado',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'CT',
        name: 'Connecticut',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'DE',
        name: 'Delaware',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'DC',
        name: 'District of Columbia',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'FL',
        name: 'Florida',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'GA',
        name: 'Georgia',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'HI',
        name: 'Hawaii',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'ID',
        name: 'Idaho',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'IL',
        name: 'Illinois',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'IN',
        name: 'Indiana',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'IA',
        name: 'Iowa',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'KS',
        name: 'Kansas',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'KY',
        name: 'Kentucky',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'LA',
        name: 'Louisiana',
        isBuyAllowed: true,
        isNftAllowed: false,
        isSellAllowed: false,
        isAllowed: true,
      },
      {
        code: 'ME',
        name: 'Maine',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MD',
        name: 'Maryland',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MA',
        name: 'Massachusetts',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MI',
        name: 'Michigan',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MN',
        name: 'Minnesota',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MS',
        name: 'Mississippi',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MO',
        name: 'Missouri',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'MT',
        name: 'Montana',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'NE',
        name: 'Nebraska',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'NV',
        name: 'Nevada',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'NH',
        name: 'New Hampshire',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'NJ',
        name: 'New Jersey',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'NM',
        name: 'New Mexico',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'NY',
        name: 'New York',
        isBuyAllowed: false,
        isNftAllowed: false,
        isSellAllowed: false,
        isAllowed: false,
      },
      {
        code: 'NC',
        name: 'North Carolina',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'ND',
        name: 'North Dakota',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'OH',
        name: 'Ohio',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'OK',
        name: 'Oklahoma',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'OR',
        name: 'Oregon',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'PA',
        name: 'Pennsylvania',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'PR',
        name: 'Puerto Rico',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'RI',
        name: 'Rhode Island',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'SC',
        name: 'South Carolina',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'SD',
        name: 'South Dakota',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'TN',
        name: 'Tennessee',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'TX',
        name: 'Texas',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: false,
        nftRestrictedFlows: ['Injection', 'Lite'],
        isAllowed: true,
      },
      {
        code: 'UT',
        name: 'Utah',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'VT',
        name: 'Vermont',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'VA',
        name: 'Virginia',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'VI',
        name: 'Virgin Islands (U.S.)',
        isBuyAllowed: false,
        isNftAllowed: false,
        isSellAllowed: false,
        isAllowed: false,
      },
      {
        code: 'WA',
        name: 'Washington',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'WV',
        name: 'West Virginia',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'WI',
        name: 'Wisconsin',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
      {
        code: 'WY',
        name: 'Wyoming',
        isBuyAllowed: true,
        isNftAllowed: true,
        isSellAllowed: true,
        isAllowed: true,
      },
    ],
    suggestedDocuments: ['driving_licence', 'national_identity_card'],
    supportedDocuments: ['driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  143: {
    alpha2: 'UY',
    alpha3: 'URY',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Uruguay',
    continent: 'South America',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
  144: {
    alpha2: 'UZ',
    alpha3: 'UZB',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Uzbekistan',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  145: {
    alpha2: 'VA',
    alpha3: 'VAT',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: true,
    name: 'Vatican City',
    continent: 'Europe',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  146: {
    alpha2: 'VN',
    alpha3: 'VNM',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Vietnam',
    continent: 'Asia',
    supportedDocuments: ['passport', 'driving_licence', 'residence_permit'],
    isAllowed: true,
  },
  147: {
    alpha2: 'EH',
    alpha3: 'ESH',
    isBuyAllowed: true,
    isNftAllowed: false,
    isSellAllowed: false,
    name: 'Western Sahara',
    continent: 'Africa',
    supportedDocuments: ['passport', 'residence_permit'],
    isAllowed: true,
  },
  148: {
    alpha2: 'ZM',
    alpha3: 'ZMB',
    isBuyAllowed: true,
    isNftAllowed: true,
    isSellAllowed: false,
    name: 'Zambia',
    continent: 'Africa',
    supportedDocuments: ['passport', 'driving_licence', 'national_identity_card', 'residence_permit'],
    isAllowed: true,
  },
}
