import { getIFOUID, IFO_POOL_STORE_TAG } from 'views/Ifos/constants'
import { mainnetTokens } from './tokens'
import { Ifo } from './types'

export const ifos: Ifo[] = [
  {
    id: 'usdc',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.bnb.address}, ${mainnetTokens.usdc.address}, ${getIFOUID(1)}>`,
    isActive: true,
    name: 'usdc',
    poolUnlimited: {
      saleAmount: '9 usdc',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.bnb,
    token: mainnetTokens.usdc,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'usdc description',
    vestingTitle: '$usdc - usdc vesting title.',
  },
  {
    id: 'sol',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.bnb.address}, ${mainnetTokens.sol.address}, ${getIFOUID(1)}>`,
    isActive: true,
    name: 'SOL',
    poolUnlimited: {
      saleAmount: '9 SOL',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.bnb,
    token: mainnetTokens.sol,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'SOL description',
    vestingTitle: '$SOL - SOL vesting title.',
  },
  {
    id: 'btc',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.cake.address}, ${mainnetTokens.bnb.address}, ${getIFOUID(1)}>`,
    isActive: false,
    name: 'BTC',
    poolUnlimited: {
      saleAmount: '9 BNB',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.cake,
    token: mainnetTokens.bnb,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'Moon description',
    vestingTitle: '$BNB - BNB vesting title.',
  },
]
