import { getIFOUID, IFO_POOL_STORE_TAG } from 'views/Ifos/constants'
import { mainnetTokens } from './tokens'
import { Ifo } from './types'

export const ifos: Ifo[] = [
  {
    id: 'BTC',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.cake.address}, ${mainnetTokens.btc.address}, ${getIFOUID(1)}>`,
    isActive: true,
    name: 'BTC',
    poolUnlimited: {
      saleAmount: '9 BTC',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.cake,
    token: mainnetTokens.btc,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'SOL description',
    vestingTitle: '$BTC - BTC vesting title.',
  },
  {
    id: 'USDC',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.cake.address}, ${mainnetTokens.usdc.address}, ${getIFOUID(1)}>`,
    isActive: true,
    name: 'USDC',
    poolUnlimited: {
      saleAmount: '9 USDC',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.cake,
    token: mainnetTokens.usdc,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'SOL description',
    vestingTitle: '$USDC - usdc vesting title.',
  },
  {
    id: 'SOL',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.cake.address}, ${mainnetTokens.sol.address}, ${getIFOUID(1)}>`,
    isActive: true,
    name: 'SOL',
    poolUnlimited: {
      saleAmount: '9 SOL',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.cake,
    token: mainnetTokens.sol,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'SOL description',
    vestingTitle: '$SOL - usdc vesting title.',
  },
  {
    id: 'BNB',
    cIFO: false,
    address: `${IFO_POOL_STORE_TAG}<${mainnetTokens.cake.address}, ${mainnetTokens.bnb.address}, ${getIFOUID(1)}>`,
    isActive: false,
    name: 'BNB',
    poolUnlimited: {
      saleAmount: '9 BNB',
      raiseAmount: '$123,456',
      cakeToBurn: '$0',
      distributionRatio: 0.7,
    },
    currency: mainnetTokens.cake,
    token: mainnetTokens.bnb,
    releaseTime: 0,
    campaignId: '1',
    articleUrl: '',
    tokenOfferingPrice: 0.00004939,
    version: 3.2,
    twitterUrl: '',
    description: 'BNB description',
    vestingTitle: '$BNB - usdc vesting title.',
  },
]
